//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMedia.UI.ProTONE.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPMedia.UI.ProTONE.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in Hibernation.
        /// </summary>
        internal static string TXT_ACT_HIBERNATE {
            get {
                return ResourceManager.GetString("TXT_ACT_HIBERNATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch a program.
        /// </summary>
        internal static string TXT_ACT_LAUNCHPROGRAM {
            get {
                return ResourceManager.GetString("TXT_ACT_LAUNCHPROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the event.
        /// </summary>
        internal static string TXT_ACT_NONE {
            get {
                return ResourceManager.GetString("TXT_ACT_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off the PC.
        /// </summary>
        internal static string TXT_ACT_SHUTDOWN {
            get {
                return ResourceManager.GetString("TXT_ACT_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter in Standby.
        /// </summary>
        internal static string TXT_ACT_STANDBY {
            get {
                return ResourceManager.GetString("TXT_ACT_STANDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bookmark.
        /// </summary>
        internal static string TXT_ADD_BOOKMARK {
            get {
                return ResourceManager.GetString("TXT_ADD_BOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name:.
        /// </summary>
        internal static string TXT_ALBUM {
            get {
                return ResourceManager.GetString("TXT_ALBUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist:.
        /// </summary>
        internal static string TXT_ARTIST {
            get {
                return ResourceManager.GetString("TXT_ARTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Embedded images:.
        /// </summary>
        internal static string TXT_ARTWORK {
            get {
                return ResourceManager.GetString("TXT_ARTWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio stream available..
        /// </summary>
        internal static string TXT_AUDIO_AVAILABLE {
            get {
                return ResourceManager.GetString("TXT_AUDIO_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files.
        /// </summary>
        internal static string TXT_AUDIO_FILES {
            get {
                return ResourceManager.GetString("TXT_AUDIO_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        internal static string TXT_AUDIOSETTINGS {
            get {
                return ResourceManager.GetString("TXT_AUDIOSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or, open one of the available DVD media in system:.
        /// </summary>
        internal static string TXT_AVAILABLE_DVD_MEDIA {
            get {
                return ResourceManager.GetString("TXT_AVAILABLE_DVD_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary rate:.
        /// </summary>
        internal static string TXT_BITRATE {
            get {
                return ResourceManager.GetString("TXT_BITRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default bookmark text (use Bookmark Manager to change).
        /// </summary>
        internal static string TXT_BOOKMARK_DEFAULT_TEXT {
            get {
                return ResourceManager.GetString("TXT_BOOKMARK_DEFAULT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark description:.
        /// </summary>
        internal static string TXT_BOOKMARK_DESC {
            get {
                return ResourceManager.GetString("TXT_BOOKMARK_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Manager.
        /// </summary>
        internal static string TXT_BOOKMARK_MANAGER {
            get {
                return ResourceManager.GetString("TXT_BOOKMARK_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark time:.
        /// </summary>
        internal static string TXT_BOOKMARK_TIME {
            get {
                return ResourceManager.GetString("TXT_BOOKMARK_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entire playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNCLEAR {
            get {
                return ResourceManager.GetString("TXT_BTNCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNDELETE {
            get {
                return ResourceManager.GetString("TXT_BTNDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNFULLSCREEN {
            get {
                return ResourceManager.GetString("TXT_BTNFULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast forward with 5 seconds.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNFWD {
            get {
                return ResourceManager.GetString("TXT_BTNFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the &apos;Jump to playlist item&apos; dialog.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNJUMPTOITEM {
            get {
                return ResourceManager.GetString("TXT_BTNJUMPTOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load new file(s).
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNLOAD {
            get {
                return ResourceManager.GetString("TXT_BTNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a new playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNLOADPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_BTNLOADPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles on/off playing in loop.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNLOOPPLAY {
            get {
                return ResourceManager.GetString("TXT_BTNLOOPPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected items with one position down in playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNMOVEDOWN {
            get {
                return ResourceManager.GetString("TXT_BTNMOVEDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected items with one position up in playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNMOVEUP {
            get {
                return ResourceManager.GetString("TXT_BTNMOVEUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to next file in playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNNEXT {
            get {
                return ResourceManager.GetString("TXT_BTNNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Load DVD media dialog.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNOPENDISK {
            get {
                return ResourceManager.GetString("TXT_BTNOPENDISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Settings dialog.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNOPENSETTINGS {
            get {
                return ResourceManager.GetString("TXT_BTNOPENSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNPAUSE {
            get {
                return ResourceManager.GetString("TXT_BTNPAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play file.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNPLAY {
            get {
                return ResourceManager.GetString("TXT_BTNPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the &apos;action on playlist end&apos;
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNPLAYLISTEND {
            get {
                return ResourceManager.GetString("TXT_BTNPLAYLISTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous file in playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNPREV {
            get {
                return ResourceManager.GetString("TXT_BTNPREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind  with 5 seconds.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNREW {
            get {
                return ResourceManager.GetString("TXT_BTNREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current playlist.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNSAVEPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_BTNSAVEPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNSTOP {
            get {
                return ResourceManager.GetString("TXT_BTNSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates playlist shuffle mode.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNTOGGLESHUFFLE {
            get {
                return ResourceManager.GetString("TXT_BTNTOGGLESHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down by 5%.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNVOLDN {
            get {
                return ResourceManager.GetString("TXT_BTNVOLDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up by 5%.
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_BTNVOLUP {
            get {
                return ResourceManager.GetString("TXT_BTNVOLUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio mode:.
        /// </summary>
        internal static string TXT_CHANNELS {
            get {
                return ResourceManager.GetString("TXT_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a bookmark.
        /// </summary>
        internal static string TXT_CMDADDBOOKMARK {
            get {
                return ResourceManager.GetString("TXT_CMDADDBOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open bookmark manager.
        /// </summary>
        internal static string TXT_CMDBOOKMARKMANAGER {
            get {
                return ResourceManager.GetString("TXT_CMDBOOKMARKMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays Audio Configuration.
        /// </summary>
        internal static string TXT_CMDCFGAUDIO {
            get {
                return ResourceManager.GetString("TXT_CMDCFGAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays Remote Control Configuration.
        /// </summary>
        internal static string TXT_CMDCFGREMOTE {
            get {
                return ResourceManager.GetString("TXT_CMDCFGREMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays Subtitles and OSD Configuration.
        /// </summary>
        internal static string TXT_CMDCFGSUBTITLES {
            get {
                return ResourceManager.GetString("TXT_CMDCFGSUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays Timer Options.
        /// </summary>
        internal static string TXT_CMDCFGTIMER {
            get {
                return ResourceManager.GetString("TXT_CMDCFGTIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays Video Configuration.
        /// </summary>
        internal static string TXT_CMDCFGVIDEO {
            get {
                return ResourceManager.GetString("TXT_CMDCFGVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entire playlist..
        /// </summary>
        internal static string TXT_CMDCLEAR {
            get {
                return ResourceManager.GetString("TXT_CMDCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected items..
        /// </summary>
        internal static string TXT_CMDDELETE {
            get {
                return ResourceManager.GetString("TXT_CMDDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen.
        /// </summary>
        internal static string TXT_CMDFULLSCREEN {
            get {
                return ResourceManager.GetString("TXT_CMDFULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast forward with 5 seconds..
        /// </summary>
        internal static string TXT_CMDFWD {
            get {
                return ResourceManager.GetString("TXT_CMDFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Bookmark Manager.
        /// </summary>
        internal static string TXT_CMDHIDEBOOKMARKMANAGER {
            get {
                return ResourceManager.GetString("TXT_CMDHIDEBOOKMARKMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the &apos;Jump to playlist item&apos; dialog.
        /// </summary>
        internal static string TXT_CMDJUMPTOITEM {
            get {
                return ResourceManager.GetString("TXT_CMDJUMPTOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load new file(s)..
        /// </summary>
        internal static string TXT_CMDLOAD {
            get {
                return ResourceManager.GetString("TXT_CMDLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a new playlist..
        /// </summary>
        internal static string TXT_CMDLOADPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_CMDLOADPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles playing in loop..
        /// </summary>
        internal static string TXT_CMDLOOPPLAY {
            get {
                return ResourceManager.GetString("TXT_CMDLOOPPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected items with one position down in playlist..
        /// </summary>
        internal static string TXT_CMDMOVEDOWN {
            get {
                return ResourceManager.GetString("TXT_CMDMOVEDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected items with one position up in playlist..
        /// </summary>
        internal static string TXT_CMDMOVEUP {
            get {
                return ResourceManager.GetString("TXT_CMDMOVEUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to next file in playlist..
        /// </summary>
        internal static string TXT_CMDNEXT {
            get {
                return ResourceManager.GetString("TXT_CMDNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Load DVD media dialog.
        /// </summary>
        internal static string TXT_CMDOPENDISK {
            get {
                return ResourceManager.GetString("TXT_CMDOPENDISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a URL.
        /// </summary>
        internal static string TXT_CMDOPENURL {
            get {
                return ResourceManager.GetString("TXT_CMDOPENURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause playback..
        /// </summary>
        internal static string TXT_CMDPAUSE {
            get {
                return ResourceManager.GetString("TXT_CMDPAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play file..
        /// </summary>
        internal static string TXT_CMDPLAY {
            get {
                return ResourceManager.GetString("TXT_CMDPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the &apos;action on playlist end&apos;.
        /// </summary>
        internal static string TXT_CMDPLAYLISTEND {
            get {
                return ResourceManager.GetString("TXT_CMDPLAYLISTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to previous file in playlist..
        /// </summary>
        internal static string TXT_CMDPREV {
            get {
                return ResourceManager.GetString("TXT_CMDPREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind with 5 seconds..
        /// </summary>
        internal static string TXT_CMDREW {
            get {
                return ResourceManager.GetString("TXT_CMDREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current playlist..
        /// </summary>
        internal static string TXT_CMDSAVEPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_CMDSAVEPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches subtitles for movie clips.
        /// </summary>
        internal static string TXT_CMDSEARCHSUBTITLES {
            get {
                return ResourceManager.GetString("TXT_CMDSEARCHSUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback..
        /// </summary>
        internal static string TXT_CMDSTOP {
            get {
                return ResourceManager.GetString("TXT_CMDSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates playlist shuffle mode..
        /// </summary>
        internal static string TXT_CMDTOGGLESHUFFLE {
            get {
                return ResourceManager.GetString("TXT_CMDTOGGLESHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down by 5%..
        /// </summary>
        internal static string TXT_CMDVOLDN {
            get {
                return ResourceManager.GetString("TXT_CMDVOLDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up by 5%..
        /// </summary>
        internal static string TXT_CMDVOLUP {
            get {
                return ResourceManager.GetString("TXT_CMDVOLUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string TXT_COMMENTS {
            get {
                return ResourceManager.GetString("TXT_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings.
        /// </summary>
        internal static string TXT_CONFIGUREAUDIO {
            get {
                return ResourceManager.GetString("TXT_CONFIGUREAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string TXT_CONFIGUREPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_CONFIGUREPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Settings.
        /// </summary>
        internal static string TXT_CONFIGURESUBTITLES {
            get {
                return ResourceManager.GetString("TXT_CONFIGURESUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Settings.
        /// </summary>
        internal static string TXT_CONFIGUREVIDEO {
            get {
                return ResourceManager.GetString("TXT_CONFIGUREVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm subtitle overwrite.
        /// </summary>
        internal static string TXT_CONFIRM_OVERWRITE_SUBTITLE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_OVERWRITE_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete bookmark.
        /// </summary>
        internal static string TXT_DELETE_BMDESC {
            get {
                return ResourceManager.GetString("TXT_DELETE_BMDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string TXT_ASSISTANCE {
            get {
                return ResourceManager.GetString("TXT_ASSISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No formatting options are specified.
        ///The program will display the file name in playlist entry..
        /// </summary>
        internal static string TXT_DISPLAY_FILENAME {
            get {
                return ResourceManager.GetString("TXT_DISPLAY_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string TXT_DURATION {
            get {
                return ResourceManager.GetString("TXT_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 Artwork Editor.
        /// </summary>
        internal static string TXT_EDITID3ARTWORK {
            get {
                return ResourceManager.GetString("TXT_EDITID3ARTWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        ///Double click to toggle remaining time.
        /// </summary>
        internal static string TXT_ELAPSED_TIME {
            get {
                return ResourceManager.GetString("TXT_ELAPSED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action on &apos;playlist ended&apos; event.
        /// </summary>
        internal static string TXT_ENABLE_PLAYLISTEVT {
            get {
                return ResourceManager.GetString("TXT_ENABLE_PLAYLISTEVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action on scheduled moment.
        /// </summary>
        internal static string TXT_ENABLE_SCHEDULEDEVT {
            get {
                return ResourceManager.GetString("TXT_ENABLE_SCHEDULEDEVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow ProTONE Player to be controlled remotely..
        /// </summary>
        internal static string TXT_ENABLEREMOTECONTROL {
            get {
                return ResourceManager.GetString("TXT_ENABLEREMOTECONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        internal static string TXT_NOTOPENED {
            get {
                return ResourceManager.GetString("TXT_NOTOPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue files at the end of current playlist.
        /// </summary>
        internal static string TXT_ENQUEUEFILES {
            get {
                return ResourceManager.GetString("TXT_ENQUEUEFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search keyword(s), separated by spaces:.
        /// </summary>
        internal static string TXT_ENTER_KEYWORD {
            get {
                return ResourceManager.GetString("TXT_ENTER_KEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback Monitor:.
        /// </summary>
        internal static string TXT_FALLBACKMONITOR {
            get {
                return ResourceManager.GetString("TXT_FALLBACKMONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fallback monitor will be used to display video contents whenever the preffered monitor is not connected to the system..
        /// </summary>
        internal static string TXT_FALLBACKMONITORDESC {
            get {
                return ResourceManager.GetString("TXT_FALLBACKMONITORDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open FFDShow Subtitle Settings ....
        /// </summary>
        internal static string TXT_FFDSHOW_SUBTITLES {
            get {
                return ResourceManager.GetString("TXT_FFDSHOW_SUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If metadata is missing, use file name parsed as:.
        /// </summary>
        internal static string TXT_FILENAME_FORMAT {
            get {
                return ResourceManager.GetString("TXT_FILENAME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types.
        /// </summary>
        internal static string TXT_FILETYPES {
            get {
                return ResourceManager.GetString("TXT_FILETYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate ProTONE Player with these file types:.
        /// </summary>
        internal static string TXT_FILETYPES_ASSOCIATIONS {
            get {
                return ResourceManager.GetString("TXT_FILETYPES_ASSOCIATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate:.
        /// </summary>
        internal static string TXT_FRAME_RATE {
            get {
                return ResourceManager.GetString("TXT_FRAME_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling frequency:.
        /// </summary>
        internal static string TXT_FREQUENCY {
            get {
                return ResourceManager.GetString("TXT_FREQUENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Genre:.
        /// </summary>
        internal static string TXT_GENRE {
            get {
                return ResourceManager.GetString("TXT_GENRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When files are launched from Windows Explorer:.
        /// </summary>
        internal static string TXT_HANDLEEXPLORERLAUNCH {
            get {
                return ResourceManager.GetString("TXT_HANDLEEXPLORERLAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put the PC into Hibernation mode.
        /// </summary>
        internal static string TXT_HIBERNATE_PC {
            get {
                return ResourceManager.GetString("TXT_HIBERNATE_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 Field Information.
        /// </summary>
        internal static string TXT_ID3INFO {
            get {
                return ResourceManager.GetString("TXT_ID3INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore mouse movement in full screen mode.
        /// </summary>
        internal static string TXT_IGNOREMOUSEMOVE {
            get {
                return ResourceManager.GetString("TXT_IGNOREMOUSEMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install component....
        /// </summary>
        internal static string TXT_INSTALLCOMPONENT {
            get {
                return ResourceManager.GetString("TXT_INSTALLCOMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have specified an invalid DVD volume. Please reselect..
        /// </summary>
        internal static string TXT_INVALIDDVDVOLUME {
            get {
                return ResourceManager.GetString("TXT_INVALIDDVDVOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to playlist item.
        /// </summary>
        internal static string TXT_JUMP_TO_ITEM {
            get {
                return ResourceManager.GetString("TXT_JUMP_TO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launch a custom program.
        /// </summary>
        internal static string TXT_LAUNCH_PROGRAM {
            get {
                return ResourceManager.GetString("TXT_LAUNCH_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch ProTONE RCC Manager ....
        /// </summary>
        internal static string TXT_LAUNCH_RCCMANAGER {
            get {
                return ResourceManager.GetString("TXT_LAUNCH_RCCMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVOL.
        /// </summary>
        internal static string TXT_LEFTVOL {
            get {
                return ResourceManager.GetString("TXT_LEFTVOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a video DVD content folder
        ///(Either a VIDEO_TS folder, or its parent):.
        /// </summary>
        internal static string TXT_LOAD_DVD_FOLDER {
            get {
                return ResourceManager.GetString("TXT_LOAD_DVD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load media files ....
        /// </summary>
        internal static string TXT_LOADMEDIAFILES {
            get {
                return ResourceManager.GetString("TXT_LOADMEDIAFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a playlist ....
        /// </summary>
        internal static string TXT_LOADPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_LOADPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching items (double click or press enter to play an item):.
        /// </summary>
        internal static string TXT_MATCHING_ITEMS {
            get {
                return ResourceManager.GetString("TXT_MATCHING_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media name: .
        /// </summary>
        internal static string TXT_MEDIA_NAME {
            get {
                return ResourceManager.GetString("TXT_MEDIA_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media is now {0}.
        /// </summary>
        internal static string TXT_MEDIA_STATE {
            get {
                return ResourceManager.GetString("TXT_MEDIA_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        internal static string TXT_MEDIA_TIME {
            get {
                return ResourceManager.GetString("TXT_MEDIA_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display notification tooltips near system tray when media state changes.
        /// </summary>
        internal static string TXT_FilterStateNOTIFICATIONSENABLED {
            get {
                return ResourceManager.GetString("TXT_FilterStateNOTIFICATIONSENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patterns available for playlist item formatting are based on combinations of these keywords:
        ///    
        ///&lt;A&gt; = artist name as in metadata;
        ///&lt;B&gt; = album name as in metadata;
        ///&lt;T&gt; = title as in metadata;
        ///&lt;C&gt; = comments as in metadata;
        ///&lt;G&gt; = genre as in metadata;
        ///&lt;#&gt; = track # as in metadata;
        ///&lt;Y&gt; = year as in metadata.    .
        /// </summary>
        internal static string TXT_METADATAPATTERNS {
            get {
                return ResourceManager.GetString("TXT_METADATAPATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not download a subtitle if the clip is shorter than
        ///(0 = always download).
        /// </summary>
        internal static string TXT_MINMOVIEDURATION {
            get {
                return ResourceManager.GetString("TXT_MINMOVIEDURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s)..
        /// </summary>
        internal static string TXT_MINUTES {
            get {
                return ResourceManager.GetString("TXT_MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc options.
        /// </summary>
        internal static string TXT_MISC_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_MISC_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings ....
        /// </summary>
        internal static string TXT_MNUAUDIO {
            get {
                return ResourceManager.GetString("TXT_MNUAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Settings ….
        /// </summary>
        internal static string TXT_MNUCFGAUDIO {
            get {
                return ResourceManager.GetString("TXT_MNUCFGAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Settings ….
        /// </summary>
        internal static string TXT_MNUCFGSUBTITLES {
            get {
                return ResourceManager.GetString("TXT_MNUCFGSUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Settings ….
        /// </summary>
        internal static string TXT_MNUCFGTIMER {
            get {
                return ResourceManager.GetString("TXT_MNUCFGTIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Settings ….
        /// </summary>
        internal static string TXT_MNUCFGVIDEO {
            get {
                return ResourceManager.GetString("TXT_MNUCFGVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear playlist.
        /// </summary>
        internal static string TXT_MNUCLEAR {
            get {
                return ResourceManager.GetString("TXT_MNUCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete playlist item.
        /// </summary>
        internal static string TXT_MNUDELETE {
            get {
                return ResourceManager.GetString("TXT_MNUDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Full Screen.
        /// </summary>
        internal static string TXT_MNUFULLSCREEN {
            get {
                return ResourceManager.GetString("TXT_MNUFULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 5 seconds.
        /// </summary>
        internal static string TXT_MNUFWD {
            get {
                return ResourceManager.GetString("TXT_MNUFWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to playlist item ....
        /// </summary>
        internal static string TXT_MNUJUMPTOITEM {
            get {
                return ResourceManager.GetString("TXT_MNUJUMPTOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load files ….
        /// </summary>
        internal static string TXT_MNULOAD {
            get {
                return ResourceManager.GetString("TXT_MNULOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Playlist ....
        /// </summary>
        internal static string TXT_MNULOADPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_MNULOADPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Play.
        /// </summary>
        internal static string TXT_MNULOOPPLAY {
            get {
                return ResourceManager.GetString("TXT_MNULOOPPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string TXT_MNUMOVEDOWN {
            get {
                return ResourceManager.GetString("TXT_MNUMOVEDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string TXT_MNUMOVEUP {
            get {
                return ResourceManager.GetString("TXT_MNUMOVEUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play next.
        /// </summary>
        internal static string TXT_MNUNEXT {
            get {
                return ResourceManager.GetString("TXT_MNUNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load DVD ….
        /// </summary>
        internal static string TXT_MNUOPENDISK {
            get {
                return ResourceManager.GetString("TXT_MNUOPENDISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings ….
        /// </summary>
        internal static string TXT_MNUOPENSETTINGS {
            get {
                return ResourceManager.GetString("TXT_MNUOPENSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open URL ….
        /// </summary>
        internal static string TXT_MNUOPENURL {
            get {
                return ResourceManager.GetString("TXT_MNUOPENURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string TXT_MNUPAUSE {
            get {
                return ResourceManager.GetString("TXT_MNUPAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string TXT_MNUPLAY {
            get {
                return ResourceManager.GetString("TXT_MNUPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist end event.
        /// </summary>
        internal static string TXT_MNUPLAYLISTEND {
            get {
                return ResourceManager.GetString("TXT_MNUPLAYLISTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play previous.
        /// </summary>
        internal static string TXT_MNUPREV {
            get {
                return ResourceManager.GetString("TXT_MNUPREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind 5 seconds.
        /// </summary>
        internal static string TXT_MNUREW {
            get {
                return ResourceManager.GetString("TXT_MNUREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Playlist ....
        /// </summary>
        internal static string TXT_MNUSAVEPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_MNUSAVEPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Options ....
        /// </summary>
        internal static string TXT_MNUSCHEDULER {
            get {
                return ResourceManager.GetString("TXT_MNUSCHEDULER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings ....
        /// </summary>
        internal static string TXT_MNUSETTINGS {
            get {
                return ResourceManager.GetString("TXT_MNUSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log file ….
        /// </summary>
        internal static string TXT_MNUSHOWLOGCONSOLE {
            get {
                return ResourceManager.GetString("TXT_MNUSHOWLOGCONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string TXT_MNUSTOP {
            get {
                return ResourceManager.GetString("TXT_MNUSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles and OSD ....
        /// </summary>
        internal static string TXT_MNUSUBTITLE {
            get {
                return ResourceManager.GetString("TXT_MNUSUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Play.
        /// </summary>
        internal static string TXT_MNUTOGGLESHUFFLE {
            get {
                return ResourceManager.GetString("TXT_MNUTOGGLESHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and Options.
        /// </summary>
        internal static string TXT_MNUTOOLS {
            get {
                return ResourceManager.GetString("TXT_MNUTOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Settings ....
        /// </summary>
        internal static string TXT_MNUVIDEO {
            get {
                return ResourceManager.GetString("TXT_MNUVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume down by 5%.
        /// </summary>
        internal static string TXT_MNUVOLDN {
            get {
                return ResourceManager.GetString("TXT_MNUVOLDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume up by 5%.
        /// </summary>
        internal static string TXT_MNUVOLUP {
            get {
                return ResourceManager.GetString("TXT_MNUVOLUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        internal static string TXT_MONITORAFFINITY {
            get {
                return ResourceManager.GetString("TXT_MONITORAFFINITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string TXT_MOVEDOWN {
            get {
                return ResourceManager.GetString("TXT_MOVEDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string TXT_MOVEUP {
            get {
                return ResourceManager.GetString("TXT_MOVEUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new bookmark.
        /// </summary>
        internal static string TXT_NEW_BMDESC {
            get {
                return ResourceManager.GetString("TXT_NEW_BMDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bookmark.
        /// </summary>
        internal static string TXT_NEW_BOOKMARK {
            get {
                return ResourceManager.GetString("TXT_NEW_BOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new bookmark was added: {0}.
        /// </summary>
        internal static string TXT_NEW_BOOKMARK_ADDED {
            get {
                return ResourceManager.GetString("TXT_NEW_BOOKMARK_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New now.
        /// </summary>
        internal static string TXT_NEWNOW {
            get {
                return ResourceManager.GetString("TXT_NEWNOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new bookmark at current playback time.
        /// </summary>
        internal static string TXT_NEWNOW_BMDESC {
            get {
                return ResourceManager.GetString("TXT_NEWNOW_BMDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No language.
        /// </summary>
        internal static string TXT_NO_LANG {
            get {
                return ResourceManager.GetString("TXT_NO_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No navigation addons are currently configured. The application cannot run without them.
        ///You must to select and enable at least one navigation addon in order to continue..
        /// </summary>
        internal static string TXT_NO_NAV_ADDONS {
            get {
                return ResourceManager.GetString("TXT_NO_NAV_ADDONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no subtitles were found for this movie clip..
        /// </summary>
        internal static string TXT_NO_SUBS_FOUND {
            get {
                return ResourceManager.GetString("TXT_NO_SUBS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is not available at this moment..
        /// </summary>
        internal static string TXT_NOT_CONFIGURABLE {
            get {
                return ResourceManager.GetString("TXT_NOT_CONFIGURABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option is not available at this moment.
        ///You must install the FFDShow codec suite in order to have actions to this option..
        /// </summary>
        internal static string TXT_NOT_CONFIGURABLE_NOFFDSHOW {
            get {
                return ResourceManager.GetString("TXT_NOT_CONFIGURABLE_NOFFDSHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display notification tooltips near system tray when subtitle download completed.
        /// </summary>
        internal static string TXT_NOTIFYSUBDOWNLOADED {
            get {
                return ResourceManager.GetString("TXT_NOTIFYSUBDOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in weekdays:.
        /// </summary>
        internal static string TXT_ONDAYS {
            get {
                return ResourceManager.GetString("TXT_ONDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-Screen Display (OSD).
        /// </summary>
        internal static string TXT_OSD {
            get {
                return ResourceManager.GetString("TXT_OSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen mode is {0}.
        /// </summary>
        internal static string TXT_OSD_FULLSCREEN {
            get {
                return ResourceManager.GetString("TXT_OSD_FULLSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string TXT_PAUSED {
            get {
                return ResourceManager.GetString("TXT_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing: {0}.
        /// </summary>
        internal static string TXT_OSD_PLAY {
            get {
                return ResourceManager.GetString("TXT_OSD_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback resumed from: {0}.
        /// </summary>
        internal static string TXT_OSD_SEEKTO {
            get {
                return ResourceManager.GetString("TXT_OSD_SEEKTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0}%.
        /// </summary>
        internal static string TXT_OSD_VOL {
            get {
                return ResourceManager.GetString("TXT_OSD_VOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Settings.
        /// </summary>
        internal static string TXT_OSDCFG {
            get {
                return ResourceManager.GetString("TXT_OSDCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Text Color.
        /// </summary>
        internal static string TXT_OSDCOLOR {
            get {
                return ResourceManager.GetString("TXT_OSDCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable On-Screen Display (OSD).
        /// </summary>
        internal static string TXT_OSDENABLED {
            get {
                return ResourceManager.GetString("TXT_OSDENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Text Font.
        /// </summary>
        internal static string TXT_OSDFONT {
            get {
                return ResourceManager.GetString("TXT_OSDFONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Text Sample.
        /// </summary>
        internal static string TXT_OSDSAMPLETEXT {
            get {
                return ResourceManager.GetString("TXT_OSDSAMPLETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Visibility Timer (seconds):.
        /// </summary>
        internal static string TXT_OSDTIMER {
            get {
                return ResourceManager.GetString("TXT_OSDTIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected movie clip already has a subtitle. 
        ///If another subtitle is found on Internet, it will overwrite the existing one.
        ///
        ///Are you sure you want to search another subtitle ?.
        /// </summary>
        internal static string TXT_OVERWRITE_SUBTITLE {
            get {
                return ResourceManager.GetString("TXT_OVERWRITE_SUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because your user account does not have administrator rights, you won&apos;t 
        ///be able to view the Supported Files and the Remote Control settings.
        ///
        ///In order to access these settings, you must launch ProTONE Player under
        ///a user account that has admin priviledges.
        /// </summary>
        internal static string TXT_PANELSHIDDEN_NOADMIN {
            get {
                return ResourceManager.GetString("TXT_PANELSHIDDEN_NOADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string TXT_OSD_PAUSED {
            get {
                return ResourceManager.GetString("TXT_OSD_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        internal static string TXT_PICTURE {
            get {
                return ResourceManager.GetString("TXT_PICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Description:.
        /// </summary>
        internal static string TXT_PICTURE_TEXT {
            get {
                return ResourceManager.GetString("TXT_PICTURE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3 Image Type:.
        /// </summary>
        internal static string TXT_PICTURE_TYPE {
            get {
                return ResourceManager.GetString("TXT_PICTURE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   from: {0}.
        /// </summary>
        internal static string TXT_PLAY_FROM {
            get {
                return ResourceManager.GetString("TXT_PLAY_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play files (replacing current playlist).
        /// </summary>
        internal static string TXT_PLAYFILES {
            get {
                return ResourceManager.GetString("TXT_PLAYFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string TXT_RUNNING {
            get {
                return ResourceManager.GetString("TXT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string TXT_PLAYLIST {
            get {
                return ResourceManager.GetString("TXT_PLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the playlist has ended.
        /// </summary>
        internal static string TXT_PLAYLIST_END_MSG {
            get {
                return ResourceManager.GetString("TXT_PLAYLIST_END_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format playlist entries as:.
        /// </summary>
        internal static string TXT_PLAYLIST_FORMAT {
            get {
                return ResourceManager.GetString("TXT_PLAYLIST_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the playlist ends ... .
        /// </summary>
        internal static string TXT_PLAYLISTEND_EVT {
            get {
                return ResourceManager.GetString("TXT_PLAYLISTEND_EVT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution: this setting is not persistent across program sessions !
        ///
        ///                    When the playlists ends:.
        /// </summary>
        internal static string TXT_PLAYLISTEVT_DESC {
            get {
                return ResourceManager.GetString("TXT_PLAYLISTEVT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        internal static string TXT_PLAYLISTOPTIONS {
            get {
                return ResourceManager.GetString("TXT_PLAYLISTOPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string TXT_PLAYLISTS {
            get {
                return ResourceManager.GetString("TXT_PLAYLISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preffered Monitor:.
        /// </summary>
        internal static string TXT_PREFERREDMONITOR {
            get {
                return ResourceManager.GetString("TXT_PREFERREDMONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preffered monitor will be used to display video contents whenever it is connected to the system..
        /// </summary>
        internal static string TXT_PREFERREDMONITORDESC {
            get {
                return ResourceManager.GetString("TXT_PREFERREDMONITORDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preferred monitor is no longer connected to the system. To choose another preffered monitor, use &apos;Restore defaults&apos; then re-select the preferred monitor..
        /// </summary>
        internal static string TXT_PREFERREDMONITORDETACHED {
            get {
                return ResourceManager.GetString("TXT_PREFERREDMONITORDETACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preffered subtitle language:.
        /// </summary>
        internal static string TXT_PREFFEREDSUBTITLELANG {
            get {
                return ResourceManager.GetString("TXT_PREFFEREDSUBTITLELANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string TXT_PRIO {
            get {
                return ResourceManager.GetString("TXT_PRIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProTONE Player is attempting to {0}. This is happening because you have configured the player to do so when {1}. Do you want to proceed ?
        ///
        ///You can abort this operation if you click Abort within the remaining time frame (see counter below). If this time elapses and you have not chosen any action, it will be assumed you have chosen to proceed..
        /// </summary>
        internal static string TXT_PROCEED_SCHEDULED_ACTION {
            get {
                return ResourceManager.GetString("TXT_PROCEED_SCHEDULED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue in ProTONE Player.
        /// </summary>
        internal static string TXT_PROTONE_ENQUEUE {
            get {
                return ResourceManager.GetString("TXT_PROTONE_ENQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play in ProTONE Player.
        /// </summary>
        internal static string TXT_PROTONE_PLAY {
            get {
                return ResourceManager.GetString("TXT_PROTONE_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time. 
        ///
        ///Double click to toggle elapsed time.
        /// </summary>
        internal static string TXT_REMAINING_TIME {
            get {
                return ResourceManager.GetString("TXT_REMAINING_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control.
        /// </summary>
        internal static string TXT_REMOTECONTROLCFG {
            get {
                return ResourceManager.GetString("TXT_REMOTECONTROLCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To define the programs and devices that are allowed to control ProTONE Player, you must use the ProTONE RCC Manager program.
        ///
        ///Click on the button below to launch ProTONE RCC Manager ....
        /// </summary>
        internal static string TXT_REMOTECONTROLDEFINITION {
            get {
                return ResourceManager.GetString("TXT_REMOTECONTROLDEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using &apos;Restore Defaults&apos; will set both the preferred and fallback monitor to the primary monitor attached to the system..
        /// </summary>
        internal static string TXT_RESTOREDEFAULTSDESC {
            get {
                return ResourceManager.GetString("TXT_RESTOREDEFAULTSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVOL.
        /// </summary>
        internal static string TXT_RIGHTVOL {
            get {
                return ResourceManager.GetString("TXT_RIGHTVOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist as ....
        /// </summary>
        internal static string TXT_SAVEPLAYLIST {
            get {
                return ResourceManager.GetString("TXT_SAVEPLAYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed with action execution ?.
        /// </summary>
        internal static string TXT_SCHEDULED_ACTION_PROCEED {
            get {
                return ResourceManager.GetString("TXT_SCHEDULED_ACTION_PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the scheduled moment has occured.
        /// </summary>
        internal static string TXT_SCHEDULED_EVENT_MSG {
            get {
                return ResourceManager.GetString("TXT_SCHEDULED_EVENT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the scheduled moment occurs:.
        /// </summary>
        internal static string TXT_SCHEDULEDEVT_DESC {
            get {
                return ResourceManager.GetString("TXT_SCHEDULEDEVT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule timer event at: .
        /// </summary>
        internal static string TXT_SCHEDULEDEVT_TIME {
            get {
                return ResourceManager.GetString("TXT_SCHEDULEDEVT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        internal static string TXT_SCHEDULERSETTINGS {
            get {
                return ResourceManager.GetString("TXT_SCHEDULERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many minutes to wait confirmation before proceeding 
        ///(0 = do not ask for confirmation, proceed directly):.
        /// </summary>
        internal static string TXT_SCHEDULERWAITTIMERPROCEED {
            get {
                return ResourceManager.GetString("TXT_SCHEDULERWAITTIMERPROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search subtitles....
        /// </summary>
        internal static string TXT_SEARCH_SUBTITLES {
            get {
                return ResourceManager.GetString("TXT_SEARCH_SUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All audio files.
        /// </summary>
        internal static string TXT_SELECT_ALLAUDIO {
            get {
                return ResourceManager.GetString("TXT_SELECT_ALLAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All playlists.
        /// </summary>
        internal static string TXT_SELECT_ALLPLAYLISTS {
            get {
                return ResourceManager.GetString("TXT_SELECT_ALLPLAYLISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All video files.
        /// </summary>
        internal static string TXT_SELECT_ALLVIDEO {
            get {
                return ResourceManager.GetString("TXT_SELECT_ALLVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load DVD Media.
        /// </summary>
        internal static string TXT_SELECT_DVD {
            get {
                return ResourceManager.GetString("TXT_SELECT_DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Device.
        /// </summary>
        internal static string TXT_SERIALDEVICE {
            get {
                return ResourceManager.GetString("TXT_SERIALDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Server Type.
        /// </summary>
        internal static string TXT_SERVERTYPE {
            get {
                return ResourceManager.GetString("TXT_SERVERTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Server URL.
        /// </summary>
        internal static string TXT_SERVERURL {
            get {
                return ResourceManager.GetString("TXT_SERVERURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate with Windows Explorer.
        /// </summary>
        internal static string TXT_SHELL_INTEGRATION {
            get {
                return ResourceManager.GetString("TXT_SHELL_INTEGRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string TXT_SHUFFLE {
            get {
                return ResourceManager.GetString("TXT_SHUFFLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shut down the PC.
        /// </summary>
        internal static string TXT_SHUTDOWN_PC {
            get {
                return ResourceManager.GetString("TXT_SHUTDOWN_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore the DVD menu (play directly first title).
        /// </summary>
        internal static string TXT_SKIP_DVD_MENU {
            get {
                return ResourceManager.GetString("TXT_SKIP_DVD_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put the PC into standby mode.
        /// </summary>
        internal static string TXT_STANDBY_PC {
            get {
                return ResourceManager.GetString("TXT_STANDBY_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string TXT_STOPPED {
            get {
                return ResourceManager.GetString("TXT_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle search has been aborted because an error has occured..
        /// </summary>
        internal static string TXT_SUB_DOWNLOAD_ERROR {
            get {
                return ResourceManager.GetString("TXT_SUB_DOWNLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: The results are sorted using these criteria (in this order): selected column, language (Preferred language on top), 
        ///prio (server order = order of subtitle servers in Subtitles/OSD Settings page). Click on a column header to select another sort citeria..
        /// </summary>
        internal static string TXT_SUB_HINTS {
            get {
                return ResourceManager.GetString("TXT_SUB_HINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the selected subtitle.
        /// </summary>
        internal static string TXT_SUB_LOAD {
            get {
                return ResourceManager.GetString("TXT_SUB_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected subtitle was successfully loaded! Enjoy!.
        /// </summary>
        internal static string TXT_SUB_LOADED {
            get {
                return ResourceManager.GetString("TXT_SUB_LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Text Color.
        /// </summary>
        internal static string TXT_SUBCOLOR {
            get {
                return ResourceManager.GetString("TXT_SUBCOLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Subtitle.
        /// </summary>
        internal static string TXT_SUBENABLED {
            get {
                return ResourceManager.GetString("TXT_SUBENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Text Font.
        /// </summary>
        internal static string TXT_SUBFONT {
            get {
                return ResourceManager.GetString("TXT_SUBFONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts and Colors.
        /// </summary>
        internal static string TXT_SUBFONTS {
            get {
                return ResourceManager.GetString("TXT_SUBFONTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Text Sample.
        /// </summary>
        internal static string TXT_SUBSAMPLETEXT {
            get {
                return ResourceManager.GetString("TXT_SUBSAMPLETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow downloading subtitles from Internet.
        /// </summary>
        internal static string TXT_SUBTITLE_DOWNLOAD {
            get {
                return ResourceManager.GetString("TXT_SUBTITLE_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following subtitles were found for this movie:.
        /// </summary>
        internal static string TXT_SUBTITLEDOWNLOADNOTIFY {
            get {
                return ResourceManager.GetString("TXT_SUBTITLEDOWNLOADNOTIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        internal static string TXT_SUBTITLES {
            get {
                return ResourceManager.GetString("TXT_SUBTITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Settings.
        /// </summary>
        internal static string TXT_SUBTITLESCFG {
            get {
                return ResourceManager.GetString("TXT_SUBTITLESCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles/OSD.
        /// </summary>
        internal static string TXT_SUBTITLESETTINGS {
            get {
                return ResourceManager.GetString("TXT_SUBTITLESETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia codecs are not installed and configured OK..
        /// </summary>
        internal static string TXT_SYSTEM_NOT_OK {
            get {
                return ResourceManager.GetString("TXT_SYSTEM_NOT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia codecs are installed and configured OK..
        /// </summary>
        internal static string TXT_SYSTEM_OK {
            get {
                return ResourceManager.GetString("TXT_SYSTEM_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string TXT_SYSTEMDIAGNOSTICS {
            get {
                return ResourceManager.GetString("TXT_SYSTEMDIAGNOSTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time scale.
        ///Click to play from position: {0}.
        /// </summary>
        internal static string TXT_TIMESCALE {
            get {
                return ResourceManager.GetString("TXT_TIMESCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time scale.
        ///Click to play from bookmark: &quot;{1}&quot;
        ///Bookmark time: {0}.
        /// </summary>
        internal static string TXT_TIMESCALE_BOOKMARK {
            get {
                return ResourceManager.GetString("TXT_TIMESCALE_BOOKMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TXT_TITLE {
            get {
                return ResourceManager.GetString("TXT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time..
        /// </summary>
        internal static string TXT_TOTAL_TIME {
            get {
                return ResourceManager.GetString("TXT_TOTAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Index:.
        /// </summary>
        internal static string TXT_TRACK {
            get {
                return ResourceManager.GetString("TXT_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio files.
        /// </summary>
        internal static string TXT_UNSELECT_ALLAUDIO {
            get {
                return ResourceManager.GetString("TXT_UNSELECT_ALLAUDIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No playlists.
        /// </summary>
        internal static string TXT_UNSELECT_ALLPLAYLISTS {
            get {
                return ResourceManager.GetString("TXT_UNSELECT_ALLPLAYLISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video files.
        /// </summary>
        internal static string TXT_UNSELECT_ALLVIDEO {
            get {
                return ResourceManager.GetString("TXT_UNSELECT_ALLVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use file metadata (e.g. ID3 fields).
        /// </summary>
        internal static string TXT_USE_METADATA {
            get {
                return ResourceManager.GetString("TXT_USE_METADATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video stream available..
        /// </summary>
        internal static string TXT_VIDEO_AVAILABLE {
            get {
                return ResourceManager.GetString("TXT_VIDEO_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video files.
        /// </summary>
        internal static string TXT_VIDEO_FILES {
            get {
                return ResourceManager.GetString("TXT_VIDEO_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Definition video files.
        /// </summary>
        internal static string TXT_VIDEO_HD_FILES {
            get {
                return ResourceManager.GetString("TXT_VIDEO_HD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video size:.
        /// </summary>
        internal static string TXT_VIDEO_SIZE {
            get {
                return ResourceManager.GetString("TXT_VIDEO_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Settings.
        /// </summary>
        internal static string TXT_VIDEOSETTINGS {
            get {
                return ResourceManager.GetString("TXT_VIDEOSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume scale.
        ///Click to set volume to: {0} %.
        /// </summary>
        internal static string TXT_VOLSCALE {
            get {
                return ResourceManager.GetString("TXT_VOLSCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string TXT_YEAR {
            get {
                return ResourceManager.GetString("TXT_YEAR", resourceCulture);
            }
        }
    }
}
