//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMedia.Utility.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPMedia.Utility.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProTONE Suite Uninstall.
        /// </summary>
        internal static string TXT_APP_NAME {
            get {
                return ResourceManager.GetString("TXT_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProTONE Suite Cleaner.
        /// </summary>
        internal static string TXT_APP_NAME2 {
            get {
                return ResourceManager.GetString("TXT_APP_NAME2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall is not complete. If you exit now, the program will not be uninstalled. You may run Uninstall again at another time to complete the uninstallation.
        ///
        ///Do you want to exit Uninstall?.
        /// </summary>
        internal static string TXT_CANCELPROMPT {
            get {
                return ResourceManager.GetString("TXT_CANCELPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cleanup process is not complete. 
        ///
        ///Do you want to exit cleanup program ?.
        /// </summary>
        internal static string TXT_CANCELPROMPT2 {
            get {
                return ResourceManager.GetString("TXT_CANCELPROMPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete log files.
        /// </summary>
        internal static string TXT_CLEAR_LOG_FILES {
            get {
                return ResourceManager.GetString("TXT_CLEAR_LOG_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify if you want to delete the log files and the application settings..
        /// </summary>
        internal static string TXT_CLEAR_USER_DATA {
            get {
                return ResourceManager.GetString("TXT_CLEAR_USER_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this data ?.
        /// </summary>
        internal static string TXT_CLEAR_USER_DATA_DESC {
            get {
                return ResourceManager.GetString("TXT_CLEAR_USER_DATA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete application settings stored in user profiles.
        /// </summary>
        internal static string TXT_CLEAR_USER_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_CLEAR_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting log files ....
        /// </summary>
        internal static string TXT_CLEARING_LOG_FILES {
            get {
                return ResourceManager.GetString("TXT_CLEARING_LOG_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user settings ....
        /// </summary>
        internal static string TXT_CLEARING_USER_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_CLEARING_USER_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup process complete..
        /// </summary>
        internal static string TXT_COMPLETE {
            get {
                return ResourceManager.GetString("TXT_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing cleanup process ....
        /// </summary>
        internal static string TXT_PREPARING_CLEANUP {
            get {
                return ResourceManager.GetString("TXT_PREPARING_CLEANUP", resourceCulture);
            }
        }
    }
}
