//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinBuilder.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkinBuilder.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge this theme into the selected file.
        ///The themes that already exist will be kept.
        ///If the selected file contains a theme with the same name, this theme will be overwritten..
        /// </summary>
        internal static string TXT_DO_MERGE {
            get {
                return ResourceManager.GetString("TXT_DO_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing. 
        ///Leave the selected file untouched and return to edit the theme..
        /// </summary>
        internal static string TXT_DO_NOTHING {
            get {
                return ResourceManager.GetString("TXT_DO_NOTHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely overwrite the selected file.
        ///The themes that already exist will be lost..
        /// </summary>
        internal static string TXT_DO_OVERWRITE {
            get {
                return ResourceManager.GetString("TXT_DO_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is default.
        /// </summary>
        internal static string TXT_IS_DEFAULT {
            get {
                return ResourceManager.GetString("TXT_IS_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you have selected contains multiple themes.
        ///What do you want to do ?.
        /// </summary>
        internal static string TXT_MULTIPLE_THEMES_IN_FILE {
            get {
                return ResourceManager.GetString("TXT_MULTIPLE_THEMES_IN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opened file(s)..
        /// </summary>
        internal static string TXT_OPENFILES {
            get {
                return ResourceManager.GetString("TXT_OPENFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a theme file:.
        /// </summary>
        internal static string TXT_OPENTHEMEFILE {
            get {
                return ResourceManager.GetString("TXT_OPENTHEMEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At program startup, remember last opened file..
        /// </summary>
        internal static string TXT_REOPEN_LAST_FILE {
            get {
                return ResourceManager.GetString("TXT_REOPEN_LAST_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last .
        /// </summary>
        internal static string TXT_RETAIN_LAST {
            get {
                return ResourceManager.GetString("TXT_RETAIN_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the theme into the file:.
        /// </summary>
        internal static string TXT_SAVETHEMEFILE {
            get {
                return ResourceManager.GetString("TXT_SAVETHEMEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an action:.
        /// </summary>
        internal static string TXT_SELECT_ACTION {
            get {
                return ResourceManager.GetString("TXT_SELECT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a theme:.
        /// </summary>
        internal static string TXT_SELECT_THEME {
            get {
                return ResourceManager.GetString("TXT_SELECT_THEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you have selected contains multiple themes. 
        ///Which one of them do you want to edit ?.
        /// </summary>
        internal static string TXT_SELECT_THEME_FROM_FILE {
            get {
                return ResourceManager.GetString("TXT_SELECT_THEME_FROM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify a theme name to use as a template.
        ///Which one of these themes do you want to use ?.
        /// </summary>
        internal static string TXT_SELECT_THEME_TEMPLATE {
            get {
                return ResourceManager.GetString("TXT_SELECT_THEME_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Builder.
        /// </summary>
        internal static string TXT_SKINBUILDERNAVIGATIONADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_SKINBUILDERNAVIGATIONADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Panel.
        /// </summary>
        internal static string TXT_SKINBUILDERPREVIEWADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_SKINBUILDERPREVIEWADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Panel.
        /// </summary>
        internal static string TXT_SKINBUILDERPROPERTYADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_SKINBUILDERPROPERTYADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Name.
        /// </summary>
        internal static string TXT_THEME_NAME {
            get {
                return ResourceManager.GetString("TXT_THEME_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPMedia Theme Files (*.thm)|*.thm||.
        /// </summary>
        internal static string TXT_THEMEFILE_FILTER {
            get {
                return ResourceManager.GetString("TXT_THEMEFILE_FILTER", resourceCulture);
            }
        }
    }
}
