//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMedia.Addons.Builtin.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPMedia.Addons.Builtin.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan aborted..
        /// </summary>
        internal static string TXT_ABORTED {
            get {
                return ResourceManager.GetString("TXT_ABORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        internal static string TXT_ADDON_FE_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_ADDON_FE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Browser.
        /// </summary>
        internal static string TXT_ADDON_MC_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_ADDON_MC_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter results by file attributes.
        /// </summary>
        internal static string TXT_ATTRIBUTESEARCH {
            get {
                return ResourceManager.GetString("TXT_ATTRIBUTESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Bit.
        /// </summary>
        internal static string TXT_BITCOPYRIGHT {
            get {
                return ResourceManager.GetString("TXT_BITCOPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC Bit.
        /// </summary>
        internal static string TXT_BITCRC {
            get {
                return ResourceManager.GetString("TXT_BITCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Bit.
        /// </summary>
        internal static string TXT_BITORIGINAL {
            get {
                return ResourceManager.GetString("TXT_BITORIGINAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Bit.
        /// </summary>
        internal static string TXT_BITPRIVATE {
            get {
                return ResourceManager.GetString("TXT_BITPRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate Mode:.
        /// </summary>
        internal static string TXT_BITRATE_MODE {
            get {
                return ResourceManager.GetString("TXT_BITRATE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize All Words.
        /// </summary>
        internal static string TXT_CAPITALIZEWORDS {
            get {
                return ResourceManager.GetString("TXT_CAPITALIZEWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Case.
        /// </summary>
        internal static string TXT_CASEINSENSITIVESEARCH {
            get {
                return ResourceManager.GetString("TXT_CASEINSENSITIVESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Wizard.
        /// </summary>
        internal static string TXT_CATALOG {
            get {
                return ResourceManager.GetString("TXT_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog description.
        /// </summary>
        internal static string TXT_CATALOG_DESC {
            get {
                return ResourceManager.GetString("TXT_CATALOG_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media catalog files (*.ctx)|*.ctx||.
        /// </summary>
        internal static string TXT_CATALOG_FILTER {
            get {
                return ResourceManager.GetString("TXT_CATALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog file information.
        /// </summary>
        internal static string TXT_CATALOGINFO {
            get {
                return ResourceManager.GetString("TXT_CATALOGINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable information.
        /// </summary>
        internal static string TXT_CATALOGITEMINFO {
            get {
                return ResourceManager.GetString("TXT_CATALOGITEMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-editable information.
        /// </summary>
        internal static string TXT_CATALOGITEMINFO_RO {
            get {
                return ResourceManager.GetString("TXT_CATALOGITEMINFO_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported items will be added to the catalog file under path: {0}.
        /// </summary>
        internal static string TXT_CATALOGPATH {
            get {
                return ResourceManager.GetString("TXT_CATALOGPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog schema version.
        /// </summary>
        internal static string TXT_CATALOGSCHEMAVERSION {
            get {
                return ResourceManager.GetString("TXT_CATALOGSCHEMAVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Ripper.
        /// </summary>
        internal static string TXT_CDRIPPERWIZARD {
            get {
                return ResourceManager.GetString("TXT_CDRIPPERWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Mode:.
        /// </summary>
        internal static string TXT_CHANNEL_MODE {
            get {
                return ResourceManager.GetString("TXT_CHANNEL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge catalogs.
        /// </summary>
        internal static string TXT_CMDCATALOGMERGE {
            get {
                return ResourceManager.GetString("TXT_CMDCATALOGMERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Catalog Import wizard.
        /// </summary>
        internal static string TXT_CMDCATALOGWIZARD {
            get {
                return ResourceManager.GetString("TXT_CMDCATALOGWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change logical disk.
        /// </summary>
        internal static string TXT_CMDCHANGEDISK {
            get {
                return ResourceManager.GetString("TXT_CMDCHANGEDISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate back.
        /// </summary>
        internal static string TXT_CMDNAVIGATEBACK {
            get {
                return ResourceManager.GetString("TXT_CMDNAVIGATEBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate forward.
        /// </summary>
        internal static string TXT_CMDNAVIGATEFORWARD {
            get {
                return ResourceManager.GetString("TXT_CMDNAVIGATEFORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to parent folder.
        /// </summary>
        internal static string TXT_CMDNAVIGATEUP {
            get {
                return ResourceManager.GetString("TXT_CMDNAVIGATEUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Tagging Wizard.
        /// </summary>
        internal static string TXT_CMDTAGGINGWIZARD {
            get {
                return ResourceManager.GetString("TXT_CMDTAGGINGWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This format does not require any configuration options..
        /// </summary>
        internal static string TXT_CONFIG_NOT_REQUIRED {
            get {
                return ResourceManager.GetString("TXT_CONFIG_NOT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change disk drive.
        /// </summary>
        internal static string TXT_DRIVES {
            get {
                return ResourceManager.GetString("TXT_DRIVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder Options: .
        /// </summary>
        internal static string TXT_ENCODEROPTIONS {
            get {
                return ResourceManager.GetString("TXT_ENCODEROPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a description for the entry to be added:.
        /// </summary>
        internal static string TXT_ENTRY_DESC {
            get {
                return ResourceManager.GetString("TXT_ENTRY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge catalogs have failed. Details:        ///
        ///{0}.
        /// </summary>
        internal static string TXT_ERR_MERGE_FAILED {
            get {
                return ResourceManager.GetString("TXT_ERR_MERGE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file does not represent a valid Media Catalog:        ///
        ///{0}.
        /// </summary>
        internal static string TXT_ERROR_INVALID_CATALOG {
            get {
                return ResourceManager.GetString("TXT_ERROR_INVALID_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot merge a catalog into itself:         ///
        ///{0}.
        /// </summary>
        internal static string TXT_ERROR_MERGE_SAME_CATALOG {
            get {
                return ResourceManager.GetString("TXT_ERROR_MERGE_SAME_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name pattern:.
        /// </summary>
        internal static string TXT_FILENAMEPATTERN {
            get {
                return ResourceManager.GetString("TXT_FILENAMEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name pattern:.
        /// </summary>
        internal static string TXT_FOLDERNAMEPATTERN {
            get {
                return ResourceManager.GetString("TXT_FOLDERNAMEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate tags based on file/folder name.
        /// </summary>
        internal static string TXT_FSTAGEDITOR {
            get {
                return ResourceManager.GetString("TXT_FSTAGEDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate tags based on CD Track Properties.
        /// </summary>
        internal static string TXT_GENERATE_TAG {
            get {
                return ResourceManager.GetString("TXT_GENERATE_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on list cells to edit them.         ///
        ///Double-click on check images to choose whether to grab a track or not..
        /// </summary>
        internal static string TXT_GRABBERHINT_STEP1 {
            get {
                return ResourceManager.GetString("TXT_GRABBERHINT_STEP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link media files to bookmark files(Hover with the mouse upon this text to show an explanatory tooltip).
        /// </summary>
        internal static string TXT_GROUP_BMKWITHMEDIA {
            get {
                return ResourceManager.GetString("TXT_GROUP_BMKWITHMEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark files (BMK) contain information about particular moments in a media file. It is very         ///
        ///important that BMK files are located near the related media files (also called &apos;parent files&apos;).          ///
        ///        ///
        ///If you ckeck this box, the File Browser will always consider that a media file and its related         ///
        ///bookmark file represent a single entity. This means that a copy, rename, move or delete operation         ///
        ///issued from the File Browser on one of these files automatically propagates to the other file too.          ///
        ///        ///
        ///Keep th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TXT_GROUP_BMKWITHMEDIA_DESC {
            get {
                return ResourceManager.GetString("TXT_GROUP_BMKWITHMEDIA_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Wizard.
        /// </summary>
        internal static string TXT_IMPORTWIZARD {
            get {
                return ResourceManager.GetString("TXT_IMPORTWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search process is initializing, please wait ....
        /// </summary>
        internal static string TXT_INIT_SEARCH {
            get {
                return ResourceManager.GetString("TXT_INIT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal media label.
        /// </summary>
        internal static string TXT_INTERNALLABEL {
            get {
                return ResourceManager.GetString("TXT_INTERNALLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Orphan.
        /// </summary>
        internal static string TXT_ISORPHAN {
            get {
                return ResourceManager.GetString("TXT_ISORPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data.
        /// </summary>
        internal static string TXT_ITEMDATA {
            get {
                return ResourceManager.GetString("TXT_ITEMDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name.
        /// </summary>
        internal static string TXT_ITEMNAME {
            get {
                return ResourceManager.GetString("TXT_ITEMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Original item type.
        /// </summary>
        internal static string TXT_ITEMTYPE_DESC {
            get {
                return ResourceManager.GetString("TXT_ITEMTYPE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to item.
        /// </summary>
        internal static string TXT_JUMPTOITEM {
            get {
                return ResourceManager.GetString("TXT_JUMPTOITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep original word casing.
        /// </summary>
        internal static string TXT_KEEPCASE {
            get {
                return ResourceManager.GetString("TXT_KEEPCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProTONE Suite uses L.A.M.E. for MP3 Encoding..
        /// </summary>
        internal static string TXT_LAME_DISCLAIMER {
            get {
                return ResourceManager.GetString("TXT_LAME_DISCLAIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Tagging Wizard ....
        /// </summary>
        internal static string TXT_LAUNCH_WIZARD {
            get {
                return ResourceManager.GetString("TXT_LAUNCH_WIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember open catalogs history.
        /// </summary>
        internal static string TXT_MAINTAIN_CATALOG_HISTORY {
            get {
                return ResourceManager.GetString("TXT_MAINTAIN_CATALOG_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. no. of files whose properties can be displayed:.
        /// </summary>
        internal static string TXT_MAXPROCESSEDFILES {
            get {
                return ResourceManager.GetString("TXT_MAXPROCESSEDFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Files with bookmarks.
        /// </summary>
        internal static string TXT_MEDIA_WITH_BOOKMARKS {
            get {
                return ResourceManager.GetString("TXT_MEDIA_WITH_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Files without bookmarks.
        /// </summary>
        internal static string TXT_MEDIA_WITHOUT_BOOKMARKS {
            get {
                return ResourceManager.GetString("TXT_MEDIA_WITHOUT_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original media label.
        /// </summary>
        internal static string TXT_MEDIALABEL {
            get {
                return ResourceManager.GetString("TXT_MEDIALABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original path within media - &apos;$&apos; stands for &apos;removable media root&apos;.
        /// </summary>
        internal static string TXT_MEDIAPATH {
            get {
                return ResourceManager.GetString("TXT_MEDIAPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original path within media.
        /// </summary>
        internal static string TXT_MEDIAPATH_SHORT {
            get {
                return ResourceManager.GetString("TXT_MEDIAPATH_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a catalog to be merged:.
        /// </summary>
        internal static string TXT_MERGECATALOG {
            get {
                return ResourceManager.GetString("TXT_MERGECATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Catalogs.
        /// </summary>
        internal static string TXT_MERGECATALOGS {
            get {
                return ResourceManager.GetString("TXT_MERGECATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3 Flags: .
        /// </summary>
        internal static string TXT_MP3FLAGS {
            get {
                return ResourceManager.GetString("TXT_MP3FLAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Files.
        /// </summary>
        internal static string TXT_MULTIRENAME {
            get {
                return ResourceManager.GetString("TXT_MULTIRENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No catalog is yet defined, please click Browse to select one..
        /// </summary>
        internal static string TXT_NO_CATALOG {
            get {
                return ResourceManager.GetString("TXT_NO_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items were found. Please change the search parameters and try again..
        /// </summary>
        internal static string TXT_NO_ITEMS_FOUND {
            get {
                return ResourceManager.GetString("TXT_NO_ITEMS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-orphan bookmark files.
        /// </summary>
        internal static string TXT_NON_ORPHAN_BOOKMARKS {
            get {
                return ResourceManager.GetString("TXT_NON_ORPHAN_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open catalog file ....
        /// </summary>
        internal static string TXT_OPENCATALOG {
            get {
                return ResourceManager.GetString("TXT_OPENCATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open catalogs..
        /// </summary>
        internal static string TXT_OPENCATALOGS {
            get {
                return ResourceManager.GetString("TXT_OPENCATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the down arrow button to open the recent files list..
        /// </summary>
        internal static string TXT_OPENRECENTFILEDROPDOWN {
            get {
                return ResourceManager.GetString("TXT_OPENRECENTFILEDROPDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open files with associated Windows program.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTIN__DEFAULTPREVIEWADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTIN__DEFAULTPREVIEWADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File System Information in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTIN__DEFAULTPROPADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTIN__DEFAULTPROPADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Properties of Bookmark Files (.BMK) in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINBOOKMARKSADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINBOOKMARKSADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Catalog Items Properties in Catalog Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERCATALOGITEMPROPFEADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERCATALOGITEMPROPFEADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Properties of Catalog Files in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERCATALOGITEMPROPMCADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINCATALOGEXPLORERCATALOGITEMPROPMCADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties of Audio CD Files (CDA) in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINCDAPROPADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINCDAPROPADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINFILEEXPLORERADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINFILEEXPLORERADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Image Files (JPG, GIF, BMP, PNG, etc.).
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINIMAGESADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINIMAGESADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play media files with the embedded ProTONE Player extension.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINPLAYERADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINPLAYERADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit audio file tags in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINTAGGEDFILEPROPADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINTAGGEDFILEPROPADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Properties of Video Files in File Browser.
        /// </summary>
        internal static string TXT_OPMEDIAADDONSBUILTINVIDEOPROPADDONPANEL {
            get {
                return ResourceManager.GetString("TXT_OPMEDIAADDONSBUILTINVIDEOPROPADDONPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Options.
        /// </summary>
        internal static string TXT_OPTIONS_ADDITIONAL {
            get {
                return ResourceManager.GetString("TXT_OPTIONS_ADDITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBR Options.
        /// </summary>
        internal static string TXT_OPTIONS_VBR {
            get {
                return ResourceManager.GetString("TXT_OPTIONS_VBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orphan bookmark files.
        /// </summary>
        internal static string TXT_ORPHAN_BOOKMARKS {
            get {
                return ResourceManager.GetString("TXT_ORPHAN_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Format:.
        /// </summary>
        internal static string TXT_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("TXT_OUTPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Media File.
        /// </summary>
        internal static string TXT_PARENTMEDIAFILE {
            get {
                return ResourceManager.GetString("TXT_PARENTMEDIAFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview results ....
        /// </summary>
        internal static string TXT_PREVIEW {
            get {
                return ResourceManager.GetString("TXT_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview results of &apos;Edit Tags&apos; task:.
        /// </summary>
        internal static string TXT_PREVIEW_DESC_EDITTAG {
            get {
                return ResourceManager.GetString("TXT_PREVIEW_DESC_EDITTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview results of &apos;Generate tags based on file/folder name&apos; task:.
        /// </summary>
        internal static string TXT_PREVIEW_DESC_FILLTAGBYFS {
            get {
                return ResourceManager.GetString("TXT_PREVIEW_DESC_FILLTAGBYFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview results of &apos;Rename Files&apos; task:.
        /// </summary>
        internal static string TXT_PREVIEW_DESC_MULTIRENAME {
            get {
                return ResourceManager.GetString("TXT_PREVIEW_DESC_MULTIRENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Results.
        /// </summary>
        internal static string TXT_PREVIEW_FORM {
            get {
                return ResourceManager.GetString("TXT_PREVIEW_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic preview timer (seconds)        ///
        ///(0 = Disable automatic preview):.
        /// </summary>
        internal static string TXT_PREVIEW_TIMER {
            get {
                return ResourceManager.GetString("TXT_PREVIEW_TIMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing CD Track no. {0} to file: {1}.
        /// </summary>
        internal static string TXT_PROCESSING_TRACK {
            get {
                return ResourceManager.GetString("TXT_PROCESSING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Metadata (e.g. tags).
        /// </summary>
        internal static string TXT_PROPERTYSEARCH {
            get {
                return ResourceManager.GetString("TXT_PROPERTYSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in subfolders.
        /// </summary>
        internal static string TXT_RECURSIVESEARCH {
            get {
                return ResourceManager.GetString("TXT_RECURSIVESEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Files.
        /// </summary>
        internal static string TXT_REMOVE_FILES {
            get {
                return ResourceManager.GetString("TXT_REMOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string TXT_RENAME {
            get {
                return ResourceManager.GetString("TXT_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Pattern:.
        /// </summary>
        internal static string TXT_RENAMEPATTERN {
            get {
                return ResourceManager.GetString("TXT_RENAMEPATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At program startup, open last loaded catalog.
        /// </summary>
        internal static string TXT_REOPEN_LAST_CATALOG {
            get {
                return ResourceManager.GetString("TXT_REOPEN_LAST_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember last.
        /// </summary>
        internal static string TXT_RETAIN_LAST {
            get {
                return ResourceManager.GetString("TXT_RETAIN_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Root Folder.
        /// </summary>
        internal static string TXT_ROOT {
            get {
                return ResourceManager.GetString("TXT_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media serial number.
        /// </summary>
        internal static string TXT_ROOTSERIALNUMBER {
            get {
                return ResourceManager.GetString("TXT_ROOTSERIALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save catalog as ....
        /// </summary>
        internal static string TXT_SAVECATALOG {
            get {
                return ResourceManager.GetString("TXT_SAVECATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save output files to:.
        /// </summary>
        internal static string TXT_SAVETOFOLDER {
            get {
                return ResourceManager.GetString("TXT_SAVETOFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan error.
        /// </summary>
        internal static string TXT_SCAN_ERROR {
            get {
                return ResourceManager.GetString("TXT_SCAN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-fatal error occured while scanning object: {0}.        ///
        ///The error message is: {1}.        ///
        ///        ///
        ///Do you want to continue scanning ?.
        /// </summary>
        internal static string TXT_SCAN_ERROR_MSG {
            get {
                return ResourceManager.GetString("TXT_SCAN_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Bookmark Files (*.BMK).
        /// </summary>
        internal static string TXT_SEARCH_BOOKMARKS {
            get {
                return ResourceManager.GetString("TXT_SEARCH_BOOKMARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Media Files.
        /// </summary>
        internal static string TXT_SEARCH_MEDIAFILES {
            get {
                return ResourceManager.GetString("TXT_SEARCH_MEDIAFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in folder:.
        /// </summary>
        internal static string TXT_SEARCHFOLDER {
            get {
                return ResourceManager.GetString("TXT_SEARCHFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the search name (allowed wildcards: *, ?)  or choose one of the predefined patterns:.
        /// </summary>
        internal static string TXT_SEARCHPATTERN_FE {
            get {
                return ResourceManager.GetString("TXT_SEARCHPATTERN_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the search name, without wildcards:.
        /// </summary>
        internal static string TXT_SEARCHPATTERN_MC {
            get {
                return ResourceManager.GetString("TXT_SEARCHPATTERN_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to be searched:.
        /// </summary>
        internal static string TXT_SEARCHVALUE {
            get {
                return ResourceManager.GetString("TXT_SEARCHVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Files and Folders.
        /// </summary>
        internal static string TXT_SEARCHWIZARD_FE {
            get {
                return ResourceManager.GetString("TXT_SEARCHWIZARD_FE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search items in catalog.
        /// </summary>
        internal static string TXT_SEARCHWIZARD_MC {
            get {
                return ResourceManager.GetString("TXT_SEARCHWIZARD_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the catalog to add the imported files to:.
        /// </summary>
        internal static string TXT_SELECTCATALOG {
            get {
                return ResourceManager.GetString("TXT_SELECTCATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Audio CD drive:.
        /// </summary>
        internal static string TXT_SELECTDRIVE {
            get {
                return ResourceManager.GetString("TXT_SELECTDRIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the insertion point within the selected catalog         ///
        ///(press F5 to reload the tree):.
        /// </summary>
        internal static string TXT_SELECTINSERTPOINT {
            get {
                return ResourceManager.GetString("TXT_SELECTINSERTPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio files to be edited ....
        /// </summary>
        internal static string TXT_SELECTTAGGEDFILES {
            get {
                return ResourceManager.GetString("TXT_SELECTTAGGEDFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder containing the audio files to be edited ....
        /// </summary>
        internal static string TXT_SELECTTAGGEDFILESFOLDER {
            get {
                return ResourceManager.GetString("TXT_SELECTTAGGEDFILESFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the tracks to be ripped from the CD:.
        /// </summary>
        internal static string TXT_SELECTTRACKS {
            get {
                return ResourceManager.GetString("TXT_SELECTTRACKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitalize first word.
        /// </summary>
        internal static string TXT_SENTENCECASE {
            get {
                return ResourceManager.GetString("TXT_SENTENCECASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         ///
        ///Shortcut: {0}.
        /// </summary>
        internal static string TXT_SHORTCUT {
            get {
                return ResourceManager.GetString("TXT_SHORTCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a description for your catalog....
        /// </summary>
        internal static string TXT_SUPPLY_CATALOG_DESC {
            get {
                return ResourceManager.GetString("TXT_SUPPLY_CATALOG_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tags.
        /// </summary>
        internal static string TXT_TAGEDITOR {
            get {
                return ResourceManager.GetString("TXT_TAGEDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Audio files (*.mp1, *.mp2, *.mp3)|*.mp1;*.mp2;*.mp3||.
        /// </summary>
        internal static string TXT_TAGGEDFILESFILTER {
            get {
                return ResourceManager.GetString("TXT_TAGGEDFILESFILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging Wizard.
        /// </summary>
        internal static string TXT_TAGGINGWIZARD {
            get {
                return ResourceManager.GetString("TXT_TAGGINGWIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagging Patterns.
        /// </summary>
        internal static string TXT_TAGINFO_PATTERNS {
            get {
                return ResourceManager.GetString("TXT_TAGINFO_PATTERNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} item(s) found. Use the right click menu to further process these items..
        /// </summary>
        internal static string TXT_TOTAL_ITEMS_FOUND {
            get {
                return ResourceManager.GetString("TXT_TOTAL_ITEMS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total items.
        /// </summary>
        internal static string TXT_TOTALCHILDRENCOUNT {
            get {
                return ResourceManager.GetString("TXT_TOTALCHILDRENCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total files.
        /// </summary>
        internal static string TXT_TOTALFILECOUNT {
            get {
                return ResourceManager.GetString("TXT_TOTALFILECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Total subfolders.
        /// </summary>
        internal static string TXT_TOTALSUBFOLDERCOUNT {
            get {
                return ResourceManager.GetString("TXT_TOTALSUBFOLDERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle the specified task type..
        /// </summary>
        internal static string TXT_UNHANDLED {
            get {
                return ResourceManager.GetString("TXT_UNHANDLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. VBR (kbps):.
        /// </summary>
        internal static string TXT_VBRMAX {
            get {
                return ResourceManager.GetString("TXT_VBRMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. VBR (kbps):.
        /// </summary>
        internal static string TXT_VBRMIN_ {
            get {
                return ResourceManager.GetString("TXT_VBRMIN:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBR Mode:.
        /// </summary>
        internal static string TXT_VBRMODE {
            get {
                return ResourceManager.GetString("TXT_VBRMODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBR Quality:.
        /// </summary>
        internal static string TXT_VBRQUALITY {
            get {
                return ResourceManager.GetString("TXT_VBRQUALITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version info not present (legacy catalog).
        /// </summary>
        internal static string TXT_VER_NA {
            get {
                return ResourceManager.GetString("TXT_VER_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while loading catalog ....
        /// </summary>
        internal static string TXT_WAIT_LOADING_CATALOG {
            get {
                return ResourceManager.GetString("TXT_WAIT_LOADING_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while merging catalogs ....
        /// </summary>
        internal static string TXT_WAIT_MERGING_CATALOG {
            get {
                return ResourceManager.GetString("TXT_WAIT_MERGING_CATALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the catalog to add the imported files to:.
        /// </summary>
        internal static string TXT_WIZCATSTEP1_DESC {
            get {
                return ResourceManager.GetString("TXT_WIZCATSTEP1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder or disk containing the items to be imported        ///
        ///(press F5 to reload the tree):.
        /// </summary>
        internal static string TXT_WIZCATSTEP2_DESC {
            get {
                return ResourceManager.GetString("TXT_WIZCATSTEP2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify which files you want to edit.         ///
        ///Use the &apos;Add Files&apos;, &apos;Add Folder&apos;,  &apos;Remove Files&apos; buttons to configure the files list..
        /// </summary>
        internal static string TXT_WIZTAGGINGSTEP1_DESC {
            get {
                return ResourceManager.GetString("TXT_WIZTAGGINGSTEP1_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify how should these files be processed:.
        /// </summary>
        internal static string TXT_WIZTAGGINGSTEP2_DESC {
            get {
                return ResourceManager.GetString("TXT_WIZTAGGINGSTEP2_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change words case:.
        /// </summary>
        internal static string TXT_WORDHANDLING {
            get {
                return ResourceManager.GetString("TXT_WORDHANDLING", resourceCulture);
            }
        }
    }
}
