//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMedia.UI.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPMedia.UI.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string TXT_ABORT {
            get {
                return ResourceManager.GetString("TXT_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string TXT_ABOUT {
            get {
                return ResourceManager.GetString("TXT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string TXT_ACTIVE {
            get {
                return ResourceManager.GetString("TXT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string TXT_ADD {
            get {
                return ResourceManager.GetString("TXT_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files ....
        /// </summary>
        internal static string TXT_ADD_FILES {
            get {
                return ResourceManager.GetString("TXT_ADD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder ....
        /// </summary>
        internal static string TXT_ADD_FOLDER {
            get {
                return ResourceManager.GetString("TXT_ADD_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*||.
        /// </summary>
        internal static string TXT_ALL_FILES_FILTER {
            get {
                return ResourceManager.GetString("TXT_ALL_FILES_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow automatic program updates.
        /// </summary>
        internal static string TXT_ALLOWAUTOUPDATES {
            get {
                return ResourceManager.GetString("TXT_ALLOWAUTOUPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        internal static string TXT_ALTKEY {
            get {
                return ResourceManager.GetString("TXT_ALTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program restart required.
        /// </summary>
        internal static string TXT_APP_RESTART {
            get {
                return ResourceManager.GetString("TXT_APP_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents ....
        /// </summary>
        internal static string TXT_APPHELP {
            get {
                return ResourceManager.GetString("TXT_APPHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string TXT_APPLY {
            get {
                return ResourceManager.GetString("TXT_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string TXT_ARCHIVE {
            get {
                return ResourceManager.GetString("TXT_ARCHIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the program&apos;s command line arguments:.
        /// </summary>
        internal static string TXT_ARGUMENTS {
            get {
                return ResourceManager.GetString("TXT_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistance.
        /// </summary>
        internal static string TXT_ASSISTANCE {
            get {
                return ResourceManager.GetString("TXT_ASSISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string TXT_ATTRIBUTES {
            get {
                return ResourceManager.GetString("TXT_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string TXT_BACK {
            get {
                return ResourceManager.GetString("TXT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse ....
        /// </summary>
        internal static string TXT_BROWSE {
            get {
                return ResourceManager.GetString("TXT_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close..
        /// </summary>
        internal static string TXT_BTNCLOSE {
            get {
                return ResourceManager.GetString("TXT_BTNCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize..
        /// </summary>
        internal static string TXT_BTNMAXIMIZE {
            get {
                return ResourceManager.GetString("TXT_BTNMAXIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize..
        /// </summary>
        internal static string TXT_BTNMINIMIZE {
            get {
                return ResourceManager.GetString("TXT_BTNMINIMIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down..
        /// </summary>
        internal static string TXT_BTNRESTOREDOWN {
            get {
                return ResourceManager.GetString("TXT_BTNRESTOREDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating object list ....
        /// </summary>
        internal static string TXT_BUILDING_OBJECT_LIST {
            get {
                return ResourceManager.GetString("TXT_BUILDING_OBJECT_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TXT_CANCEL {
            get {
                return ResourceManager.GetString("TXT_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution.
        /// </summary>
        internal static string TXT_CAUTION {
            get {
                return ResourceManager.GetString("TXT_CAUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        internal static string TXT_CHANGE {
            get {
                return ResourceManager.GetString("TXT_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check program updates.
        /// </summary>
        internal static string TXT_CHECKUPDATE {
            get {
                return ResourceManager.GetString("TXT_CHECKUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color:.
        /// </summary>
        internal static string TXT_CHOOSE_COLOR {
            get {
                return ResourceManager.GetString("TXT_CHOOSE_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder to be added as favorite:.
        /// </summary>
        internal static string TXT_CHOOSE_FAVORITE {
            get {
                return ResourceManager.GetString("TXT_CHOOSE_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the folder to store the log files:.
        /// </summary>
        internal static string TXT_CHOOSELOGPATH {
            get {
                return ResourceManager.GetString("TXT_CHOOSELOGPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the program to be executed:.
        /// </summary>
        internal static string TXT_CHOOSEPROGRAM {
            get {
                return ResourceManager.GetString("TXT_CHOOSEPROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the program working folder:.
        /// </summary>
        internal static string TXT_CHOOSEWORKDIR {
            get {
                return ResourceManager.GetString("TXT_CHOOSEWORKDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log File.
        /// </summary>
        internal static string TXT_CLEARLOG {
            get {
                return ResourceManager.GetString("TXT_CLEARLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Window.
        /// </summary>
        internal static string TXT_CLEARWINDOW {
            get {
                return ResourceManager.GetString("TXT_CLEARWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on list cells to edit them..
        /// </summary>
        internal static string TXT_CLICK_LIST_TO_EDIT {
            get {
                return ResourceManager.GetString("TXT_CLICK_LIST_TO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Keyboard Shortcuts..
        /// </summary>
        internal static string TXT_CMDCFGKEYBOARD {
            get {
                return ResourceManager.GetString("TXT_CMDCFGKEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open favorite folder manager.
        /// </summary>
        internal static string TXT_CMDFAVMANAGER {
            get {
                return ResourceManager.GetString("TXT_CMDFAVMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Changes..
        /// </summary>
        internal static string TXT_CMDGENERICAPPLY {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICAPPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy data (or files).
        /// </summary>
        internal static string TXT_CMDGENERICCOPY {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICCOPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut data (or files).
        /// </summary>
        internal static string TXT_CMDGENERICCUT {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data (or files).
        /// </summary>
        internal static string TXT_CMDGENERICDELETE {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Document..
        /// </summary>
        internal static string TXT_CMDGENERICNEW {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document..
        /// </summary>
        internal static string TXT_CMDGENERICOPEN {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste data (or files).
        /// </summary>
        internal static string TXT_CMDGENERICPASTE {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICPASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh data.
        /// </summary>
        internal static string TXT_CMDGENERICREFRESH {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICREFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files.
        /// </summary>
        internal static string TXT_CMDGENERICRENAME {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICRENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Document..
        /// </summary>
        internal static string TXT_CMDGENERICSAVE {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search data (or files).
        /// </summary>
        internal static string TXT_CMDGENERICSEARCH {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo changes..
        /// </summary>
        internal static string TXT_CMDGENERICUNDO {
            get {
                return ResourceManager.GetString("TXT_CMDGENERICUNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open help file.
        /// </summary>
        internal static string TXT_CMDOPENHELP {
            get {
                return ResourceManager.GetString("TXT_CMDOPENHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Settings dialog..
        /// </summary>
        internal static string TXT_CMDOPENSETTINGS {
            get {
                return ResourceManager.GetString("TXT_CMDOPENSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the log file console.
        /// </summary>
        internal static string TXT_CMDSHOWLOGCONSOLE {
            get {
                return ResourceManager.GetString("TXT_CMDSHOWLOGCONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between addon windows..
        /// </summary>
        internal static string TXT_CMDSWITCHWINDOWS {
            get {
                return ResourceManager.GetString("TXT_CMDSWITCHWINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command name.
        /// </summary>
        internal static string TXT_COMMAND {
            get {
                return ResourceManager.GetString("TXT_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string TXT_CONFIRM {
            get {
                return ResourceManager.GetString("TXT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation ?.
        /// </summary>
        internal static string TXT_CONFIRM_ABORT {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_ABORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} does not exist yet.
        ///Do you want to create it ?.
        /// </summary>
        internal static string TXT_CONFIRM_CREATE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the file:
        ///{0} ?.
        /// </summary>
        internal static string TXT_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder: {0} is not empty. 
        ///Do you want to delete it (including its contents) ?.
        /// </summary>
        internal static string TXT_CONFIRM_DELETE_DIR {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_DELETE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the folder:
        ///{0} ?.
        /// </summary>
        internal static string TXT_CONFIRM_DELETE_EMPTYDIR {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_DELETE_EMPTYDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is has one or more of these attributes: Read-Only/Hidden/System.
        ///Do you still want to delete it ?.
        /// </summary>
        internal static string TXT_CONFIRM_DELETE_ROHS {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_DELETE_ROHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move the file:
        ///{0} ?.
        /// </summary>
        internal static string TXT_CONFIRM_MOVE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder: {0} is not empty. 
        ///Do you want to move it and all its contents ?.
        /// </summary>
        internal static string TXT_CONFIRM_MOVE_DIR {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_MOVE_DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move the folder:
        ///{0} ?.
        /// </summary>
        internal static string TXT_CONFIRM_MOVE_EMPTYDIR {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_MOVE_EMPTYDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is has one or more of these attributes: Read-Only/Hidden/System.
        ///Do you still want to move it ?.
        /// </summary>
        internal static string TXT_CONFIRM_MOVE_ROHS {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_MOVE_ROHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination file {0} already exists. 
        ///Do you want to overwrite it ?.
        /// </summary>
        internal static string TXT_CONFIRM_OVERWRITE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination file {0} already exists and it is a Read-Only file. 
        ///Do you want to overwrite it ?.
        /// </summary>
        internal static string TXT_CONFIRM_OVERWRITE_RO {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_OVERWRITE_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item properties were changed. Do you want to save changes ?.
        /// </summary>
        internal static string TXT_CONFIRM_PROPERTYSAVE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_PROPERTYSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load the default settings?.
        /// </summary>
        internal static string TXT_CONFIRM_RESTORE {
            get {
                return ResourceManager.GetString("TXT_CONFIRM_RESTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes ?.
        /// </summary>
        internal static string TXT_CONFIRMSAVECHANGES {
            get {
                return ResourceManager.GetString("TXT_CONFIRMSAVECHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm program update.
        /// </summary>
        internal static string TXT_CONFIRMUPDATE {
            get {
                return ResourceManager.GetString("TXT_CONFIRMUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TXT_COPY {
            get {
                return ResourceManager.GetString("TXT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string TXT_CREATIONDATE {
            get {
                return ResourceManager.GetString("TXT_CREATIONDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} items out of {2} ({3}% done).
        /// </summary>
        internal static string TXT_CUR_PROGRESS {
            get {
                return ResourceManager.GetString("TXT_CUR_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path: {0}.
        /// </summary>
        internal static string TXT_CURRENT_PATH {
            get {
                return ResourceManager.GetString("TXT_CURRENT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string TXT_CUT {
            get {
                return ResourceManager.GetString("TXT_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Please define the program to be executed ].
        /// </summary>
        internal static string TXT_DEFINE_PROGRAM {
            get {
                return ResourceManager.GetString("TXT_DEFINE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Define the proxy server address ].
        /// </summary>
        internal static string TXT_DEFINE_PROXYSERVERADDRESS {
            get {
                return ResourceManager.GetString("TXT_DEFINE_PROXYSERVERADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Define the proxy server username ].
        /// </summary>
        internal static string TXT_DEFINE_PROXYSERVERUSERNAME {
            get {
                return ResourceManager.GetString("TXT_DEFINE_PROXYSERVERUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TXT_DELETE {
            get {
                return ResourceManager.GetString("TXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TXT_DESC {
            get {
                return ResourceManager.GetString("TXT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string TXT_DESC_COPY_TASK {
            get {
                return ResourceManager.GetString("TXT_DESC_COPY_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        internal static string TXT_DESC_DELETE_TASK {
            get {
                return ResourceManager.GetString("TXT_DESC_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving.
        /// </summary>
        internal static string TXT_DESC_MOVE_TASK {
            get {
                return ResourceManager.GetString("TXT_DESC_MOVE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command description.
        /// </summary>
        internal static string TXT_DESCRIPTION {
            get {
                return ResourceManager.GetString("TXT_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string TXT_DISABLE {
            get {
                return ResourceManager.GetString("TXT_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic updates.
        /// </summary>
        internal static string TXT_DISABLEAUTODOWNLOADS {
            get {
                return ResourceManager.GetString("TXT_DISABLEAUTODOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical disc (CD, DVD or BlueRay).
        /// </summary>
        internal static string TXT_DISK_CDR {
            get {
                return ResourceManager.GetString("TXT_DISK_CDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TXT_DISK_FIL {
            get {
                return ResourceManager.GetString("TXT_DISK_FIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string TXT_DISK_FLD {
            get {
                return ResourceManager.GetString("TXT_DISK_FLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed disk (hard disk).
        /// </summary>
        internal static string TXT_DISK_HDD {
            get {
                return ResourceManager.GetString("TXT_DISK_HDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network drive.
        /// </summary>
        internal static string TXT_DISK_NET {
            get {
                return ResourceManager.GetString("TXT_DISK_NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk without root folder.
        /// </summary>
        internal static string TXT_DISK_NRT {
            get {
                return ResourceManager.GetString("TXT_DISK_NRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual RAM disk.
        /// </summary>
        internal static string TXT_DISK_RAM {
            get {
                return ResourceManager.GetString("TXT_DISK_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable disk (Floppy disk or USB flash)..
        /// </summary>
        internal static string TXT_DISK_REM {
            get {
                return ResourceManager.GetString("TXT_DISK_REM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown disk type.
        /// </summary>
        internal static string TXT_DISK_UNK {
            get {
                return ResourceManager.GetString("TXT_DISK_UNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double click to edit.
        /// </summary>
        internal static string TXT_DOUBLE_CLICK_TO_EDIT {
            get {
                return ResourceManager.GetString("TXT_DOUBLE_CLICK_TO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string TXT_DOWNLOAD {
            get {
                return ResourceManager.GetString("TXT_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw skinned borders and title bar (recommended).
        /// </summary>
        internal static string TXT_DRAWBORDERS {
            get {
                return ResourceManager.GetString("TXT_DRAWBORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  [{1}]  [{2}]  [{3} MB free]  [{4}].
        /// </summary>
        internal static string TXT_DRIVE_DESC_FORMAT {
            get {
                return ResourceManager.GetString("TXT_DRIVE_DESC_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key combination &apos;{0}&apos; is already assigned to &apos;{1}&apos;.
        ///Do you want to re-assign it to &apos;{2}&apos;?.
        /// </summary>
        internal static string TXT_DUP_SHORTCUT_CONFIRM {
            get {
                return ResourceManager.GetString("TXT_DUP_SHORTCUT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key combination &apos;{0}&apos; is already assigned to &apos;{1}&apos; and cannot be modified.
        ///Please enter a different combination..
        /// </summary>
        internal static string TXT_DUP_SHORTCUT_FIXED {
            get {
                return ResourceManager.GetString("TXT_DUP_SHORTCUT_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut is already in use.
        /// </summary>
        internal static string TXT_DUPPLICATE_SHORTCUT {
            get {
                return ResourceManager.GetString("TXT_DUPPLICATE_SHORTCUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TXT_EDIT {
            get {
                return ResourceManager.GetString("TXT_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the new key combination for: {0}.
        ///Current shortcut is: {1}..
        /// </summary>
        internal static string TXT_EDITKEYDESC {
            get {
                return ResourceManager.GetString("TXT_EDITKEYDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string TXT_ENABLE {
            get {
                return ResourceManager.GetString("TXT_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable program logging.
        /// </summary>
        internal static string TXT_ENABLE_LOG {
            get {
                return ResourceManager.GetString("TXT_ENABLE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string TXT_ENABLED {
            get {
                return ResourceManager.GetString("TXT_ENABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable skinned borders.
        /// </summary>
        internal static string TXT_ENABLESKINNEDBORDERS {
            get {
                return ResourceManager.GetString("TXT_ENABLESKINNEDBORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TXT_ERROR {
            get {
                return ResourceManager.GetString("TXT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error messages.
        /// </summary>
        internal static string TXT_ERRORS {
            get {
                return ResourceManager.GetString("TXT_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors appeared while copying the specified files.
        ///More details in the list below..
        /// </summary>
        internal static string TXT_ERRORS_COPY_TASK {
            get {
                return ResourceManager.GetString("TXT_ERRORS_COPY_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors appeared while deleting the specified files.
        ///More details in the list below..
        /// </summary>
        internal static string TXT_ERRORS_DELETE_TASK {
            get {
                return ResourceManager.GetString("TXT_ERRORS_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors appeared during the operation..
        /// </summary>
        internal static string TXT_ERRORS_ENCOUNTERED {
            get {
                return ResourceManager.GetString("TXT_ERRORS_ENCOUNTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors appeared while moving the specified files.
        ///More details in the list below..
        /// </summary>
        internal static string TXT_ERRORS_MOVE_TASK {
            get {
                return ResourceManager.GetString("TXT_ERRORS_MOVE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        internal static string TXT_EVERYDAY {
            get {
                return ResourceManager.GetString("TXT_EVERYDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TXT_EXIT {
            get {
                return ResourceManager.GetString("TXT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string TXT_EXPORT {
            get {
                return ResourceManager.GetString("TXT_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full export ....
        /// </summary>
        internal static string TXT_EXPORT_FULL {
            get {
                return ResourceManager.GetString("TXT_EXPORT_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial export ....
        /// </summary>
        internal static string TXT_EXPORT_PARTIAL {
            get {
                return ResourceManager.GetString("TXT_EXPORT_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string TXT_EXTENSION {
            get {
                return ResourceManager.GetString("TXT_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string TXT_FAVORITES {
            get {
                return ResourceManager.GetString("TXT_FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorite Folders.
        /// </summary>
        internal static string TXT_FAVORITES_ADD {
            get {
                return ResourceManager.GetString("TXT_FAVORITES_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorite Folders ....
        /// </summary>
        internal static string TXT_FAVORITES_MANAGE {
            get {
                return ResourceManager.GetString("TXT_FAVORITES_MANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string TXT_FILE {
            get {
                return ResourceManager.GetString("TXT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string TXT_FILE_TYPE {
            get {
                return ResourceManager.GetString("TXT_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string TXT_FILENAME {
            get {
                return ResourceManager.GetString("TXT_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string TXT_FILESIZE {
            get {
                return ResourceManager.GetString("TXT_FILESIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Information.
        /// </summary>
        internal static string TXT_FILESYSTEMINFO {
            get {
                return ResourceManager.GetString("TXT_FILESYSTEMINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///Errors.
        /// </summary>
        internal static string TXT_FLAG_ERRORS {
            get {
                return ResourceManager.GetString("TXT_FLAG_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///Information.
        /// </summary>
        internal static string TXT_FLAG_INFOS {
            get {
                return ResourceManager.GetString("TXT_FLAG_INFOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///Debug Traces.
        /// </summary>
        internal static string TXT_FLAG_TRACES {
            get {
                return ResourceManager.GetString("TXT_FLAG_TRACES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show
        ///Warnings.
        /// </summary>
        internal static string TXT_FLAG_WARNINGS {
            get {
                return ResourceManager.GetString("TXT_FLAG_WARNINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is no longer accessible. It may have been moved, removed, or its disk could have been removed from the computer..
        /// </summary>
        internal static string TXT_FOLDERNOTACCESSIBLE {
            get {
                return ResourceManager.GetString("TXT_FOLDERNOTACCESSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font:.
        /// </summary>
        internal static string TXT_FONT {
            get {
                return ResourceManager.GetString("TXT_FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font style:.
        /// </summary>
        internal static string TXT_FONT_STYLE {
            get {
                return ResourceManager.GetString("TXT_FONT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format.
        /// </summary>
        internal static string TXT_FORMAT_UNKNOWN {
            get {
                return ResourceManager.GetString("TXT_FORMAT_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string TXT_FORWARD {
            get {
                return ResourceManager.GetString("TXT_FORWARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Window.
        /// </summary>
        internal static string TXT_FREEZEWINDOW {
            get {
                return ResourceManager.GetString("TXT_FREEZEWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string TXT_FRIDAY {
            get {
                return ResourceManager.GetString("TXT_FRIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable detailed debug logging.
        /// </summary>
        internal static string TXT_HEAVY_TRACE {
            get {
                return ResourceManager.GetString("TXT_HEAVY_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TXT_HELP {
            get {
                return ResourceManager.GetString("TXT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string TXT_HIDDEN {
            get {
                return ResourceManager.GetString("TXT_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy.
        /// </summary>
        internal static string TXT_HTTPPROXY {
            get {
                return ResourceManager.GetString("TXT_HTTPPROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Internet Explorer proxy settings.
        /// </summary>
        internal static string TXT_IEPROXY {
            get {
                return ResourceManager.GetString("TXT_IEPROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string TXT_IMPORT {
            get {
                return ResourceManager.GetString("TXT_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full import ....
        /// </summary>
        internal static string TXT_IMPORT_FULL {
            get {
                return ResourceManager.GetString("TXT_IMPORT_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial import (with merge)....
        /// </summary>
        internal static string TXT_IMPORT_PARTIAL {
            get {
                return ResourceManager.GetString("TXT_IMPORT_PARTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log info messages.
        /// </summary>
        internal static string TXT_INFO {
            get {
                return ResourceManager.GetString("TXT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data.
        /// </summary>
        internal static string TXT_INPUT_DATA {
            get {
                return ResourceManager.GetString("TXT_INPUT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert disk.
        /// </summary>
        internal static string TXT_INSERT_DISK {
            get {
                return ResourceManager.GetString("TXT_INSERT_DISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the disk labeled {0} (desc: {1}) into the {2} drive..
        /// </summary>
        internal static string TXT_INSERT_MEDIA {
            get {
                return ResourceManager.GetString("TXT_INSERT_MEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep window on top of others.
        /// </summary>
        internal static string TXT_KEEPONTOP {
            get {
                return ResourceManager.GetString("TXT_KEEPONTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut.
        /// </summary>
        internal static string TXT_KEY {
            get {
                return ResourceManager.GetString("TXT_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define keys for {0}.
        /// </summary>
        internal static string TXT_KEYCOMMANDEDITOR {
            get {
                return ResourceManager.GetString("TXT_KEYCOMMANDEDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string TXT_LANGUAGE {
            get {
                return ResourceManager.GetString("TXT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest access.
        /// </summary>
        internal static string TXT_LASTACCESSDATE {
            get {
                return ResourceManager.GetString("TXT_LASTACCESSDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest change.
        /// </summary>
        internal static string TXT_LASTCHANGEDATE {
            get {
                return ResourceManager.GetString("TXT_LASTCHANGEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string TXT_LEVEL_AUTOMATIC {
            get {
                return ResourceManager.GetString("TXT_LEVEL_AUTOMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TXT_LEVEL_ERROR {
            get {
                return ResourceManager.GetString("TXT_LEVEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string TXT_LEVEL_EXCEPTION {
            get {
                return ResourceManager.GetString("TXT_LEVEL_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed debug trace.
        /// </summary>
        internal static string TXT_LEVEL_HEAVYTRACE {
            get {
                return ResourceManager.GetString("TXT_LEVEL_HEAVYTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string TXT_LEVEL_INFO {
            get {
                return ResourceManager.GetString("TXT_LEVEL_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        internal static string TXT_LEVEL_TRACE {
            get {
                return ResourceManager.GetString("TXT_LEVEL_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TXT_LEVEL_WARNING {
            get {
                return ResourceManager.GetString("TXT_LEVEL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program version is built with enforced logging.
        ///All log level are enabled by default..
        /// </summary>
        internal static string TXT_LOG_DESC {
            get {
                return ResourceManager.GetString("TXT_LOG_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many days to keep the old log files 
        ///(min=2, max=10):.
        /// </summary>
        internal static string TXT_LOG_KEEPDAYS {
            get {
                return ResourceManager.GetString("TXT_LOG_KEEPDAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files path:.
        /// </summary>
        internal static string TXT_LOG_PATH {
            get {
                return ResourceManager.GetString("TXT_LOG_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files (*.log)|*.log||.
        /// </summary>
        internal static string TXT_LOGFILE_FILTER {
            get {
                return ResourceManager.GetString("TXT_LOGFILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file name:.
        /// </summary>
        internal static string TXT_LOGFILENAME {
            get {
                return ResourceManager.GetString("TXT_LOGFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file console.
        /// </summary>
        internal static string TXT_LOGLINECONSOLE {
            get {
                return ResourceManager.GetString("TXT_LOGLINECONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log entries count:.
        /// </summary>
        internal static string TXT_LOGLINECOUNT {
            get {
                return ResourceManager.GetString("TXT_LOGLINECOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        internal static string TXT_LOGMESSAGE {
            get {
                return ResourceManager.GetString("TXT_LOGMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look in.
        /// </summary>
        internal static string TXT_LOOK_IN {
            get {
                return ResourceManager.GetString("TXT_LOOK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define your Favorite Folders:.
        /// </summary>
        internal static string TXT_MANAGE_FAVORITES {
            get {
                return ResourceManager.GetString("TXT_MANAGE_FAVORITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string TXT_MODIFY {
            get {
                return ResourceManager.GetString("TXT_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        internal static string TXT_MODULENAME {
            get {
                return ResourceManager.GetString("TXT_MODULENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string TXT_MONDAY {
            get {
                return ResourceManager.GetString("TXT_MONDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Multiple Files.
        /// </summary>
        internal static string TXT_MULTIRENAME {
            get {
                return ResourceManager.GetString("TXT_MULTIRENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string TXT_NA {
            get {
                return ResourceManager.GetString("TXT_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TXT_NAME {
            get {
                return ResourceManager.GetString("TXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string TXT_NEW {
            get {
                return ResourceManager.GetString("TXT_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file name.
        /// </summary>
        internal static string TXT_NEW_FILENAME {
            get {
                return ResourceManager.GetString("TXT_NEW_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        internal static string TXT_NEW_FOLDER {
            get {
                return ResourceManager.GetString("TXT_NEW_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TXT_NO {
            get {
                return ResourceManager.GetString("TXT_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No label.
        /// </summary>
        internal static string TXT_NO_LABEL {
            get {
                return ResourceManager.GetString("TXT_NO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name.
        /// </summary>
        internal static string TXT_NO_NAME {
            get {
                return ResourceManager.GetString("TXT_NO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: There is no operational network connection..
        /// </summary>
        internal static string TXT_NO_NETWORK {
            get {
                return ResourceManager.GetString("TXT_NO_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy.
        /// </summary>
        internal static string TXT_NOPROXY {
            get {
                return ResourceManager.GetString("TXT_NOPROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready.
        /// </summary>
        internal static string TXT_NOT_READY {
            get {
                return ResourceManager.GetString("TXT_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new program version is available: {0}.
        ///Do you want to update to this version?.
        /// </summary>
        internal static string TXT_NOTIFYUPDATE {
            get {
                return ResourceManager.GetString("TXT_NOTIFYUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program has the latest available version.
        ///
        ///For the moment, you do not need to update the program..
        /// </summary>
        internal static string TXT_NOUPDATEREQUIRED {
            get {
                return ResourceManager.GetString("TXT_NOUPDATEREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string TXT_OFF {
            get {
                return ResourceManager.GetString("TXT_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TXT_OK {
            get {
                return ResourceManager.GetString("TXT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old file name.
        /// </summary>
        internal static string TXT_OLD_FILENAME {
            get {
                return ResourceManager.GetString("TXT_OLD_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string TXT_ON {
            get {
                return ResourceManager.GetString("TXT_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string TXT_OPEN {
            get {
                return ResourceManager.GetString("TXT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string TXT_OR {
            get {
                return ResourceManager.GetString("TXT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output data.
        /// </summary>
        internal static string TXT_OUTPUT_DATA {
            get {
                return ResourceManager.GetString("TXT_OUTPUT_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent folder.
        /// </summary>
        internal static string TXT_PARENT {
            get {
                return ResourceManager.GetString("TXT_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TXT_PASSWORD {
            get {
                return ResourceManager.GetString("TXT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TXT_PASTE {
            get {
                return ResourceManager.GetString("TXT_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string TXT_PATH {
            get {
                return ResourceManager.GetString("TXT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        internal static string TXT_PID {
            get {
                return ResourceManager.GetString("TXT_PID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Name:.
        /// </summary>
        internal static string TXT_PORT_NAME {
            get {
                return ResourceManager.GetString("TXT_PORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port Settings:.
        /// </summary>
        internal static string TXT_PORT_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_PORT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [PRIMARY MONITOR].
        /// </summary>
        internal static string TXT_PRIMARY_MONITOR {
            get {
                return ResourceManager.GetString("TXT_PRIMARY_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string TXT_PROCEED {
            get {
                return ResourceManager.GetString("TXT_PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file.
        /// </summary>
        internal static string TXT_PROCESSING_FILE {
            get {
                return ResourceManager.GetString("TXT_PROCESSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program to be executed (click on the link below to change):.
        /// </summary>
        internal static string TXT_PROGRAM_DEF {
            get {
                return ResourceManager.GetString("TXT_PROGRAM_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe)|*.exe|All files (*.*)|*.*||.
        /// </summary>
        internal static string TXT_PROGRAMS_FILTER {
            get {
                return ResourceManager.GetString("TXT_PROGRAMS_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program startup information.
        /// </summary>
        internal static string TXT_PROGRAMSTARTUPINFO {
            get {
                return ResourceManager.GetString("TXT_PROGRAMSTARTUPINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server address:.
        /// </summary>
        internal static string TXT_PROXYADDRESS {
            get {
                return ResourceManager.GetString("TXT_PROXYADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string TXT_PROXYPASSWORD {
            get {
                return ResourceManager.GetString("TXT_PROXYPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server port:.
        /// </summary>
        internal static string TXT_PROXYPORT {
            get {
                return ResourceManager.GetString("TXT_PROXYPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy server type:.
        /// </summary>
        internal static string TXT_PROXYTYPE {
            get {
                return ResourceManager.GetString("TXT_PROXYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        internal static string TXT_PROXYUSERNAME {
            get {
                return ResourceManager.GetString("TXT_PROXYUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only.
        /// </summary>
        internal static string TXT_READONLY {
            get {
                return ResourceManager.GetString("TXT_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TXT_READY {
            get {
                return ResourceManager.GetString("TXT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string TXT_REFRESH {
            get {
                return ResourceManager.GetString("TXT_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore defaults.
        /// </summary>
        internal static string TXT_RESTOREDEFAULTS {
            get {
                return ResourceManager.GetString("TXT_RESTOREDEFAULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;Restore Defaults&apos; to load the default keyboard shortcut configuration..
        /// </summary>
        internal static string TXT_RESTORESHORTCUTSDESC {
            get {
                return ResourceManager.GetString("TXT_RESTORESHORTCUTSDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results:.
        /// </summary>
        internal static string TXT_RESULTS {
            get {
                return ResourceManager.GetString("TXT_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string TXT_S_GENERALSETTINGS {
            get {
                return ResourceManager.GetString("TXT_S_GENERALSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard
        ///Map.
        /// </summary>
        internal static string TXT_S_KEYMAP {
            get {
                return ResourceManager.GetString("TXT_S_KEYMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit a shortcut, click on its associated links in the table below. The shortcuts with disabled links cannot be changed by the user (e.g: OpenHelp = F1, etc)..
        /// </summary>
        internal static string TXT_S_KEYMAP_DESC {
            get {
                return ResourceManager.GetString("TXT_S_KEYMAP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log 
        ///File.
        /// </summary>
        internal static string TXT_S_LOGGINGSETTINGS {
            get {
                return ResourceManager.GetString("TXT_S_LOGGINGSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        internal static string TXT_S_NETWORK_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_S_NETWORK_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        internal static string TXT_SAMPLE {
            get {
                return ResourceManager.GetString("TXT_SAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string TXT_SATURDAY {
            get {
                return ResourceManager.GetString("TXT_SATURDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TXT_SAVE {
            get {
                return ResourceManager.GetString("TXT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string TXT_SAVE_AS {
            get {
                return ResourceManager.GetString("TXT_SAVE_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log file as ....
        /// </summary>
        internal static string TXT_SAVELOGFILE {
            get {
                return ResourceManager.GetString("TXT_SAVELOGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save partial log file as:.
        /// </summary>
        internal static string TXT_SAVELOGFILE_PART {
            get {
                return ResourceManager.GetString("TXT_SAVELOGFILE_PART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log file or window.
        /// </summary>
        internal static string TXT_SAVELOGORWINDOW {
            get {
                return ResourceManager.GetString("TXT_SAVELOGORWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save log window as ....
        /// </summary>
        internal static string TXT_SAVEWINDOW {
            get {
                return ResourceManager.GetString("TXT_SAVEWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        internal static string TXT_SCANNING {
            get {
                return ResourceManager.GetString("TXT_SCANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character set:.
        /// </summary>
        internal static string TXT_SCRIPT {
            get {
                return ResourceManager.GetString("TXT_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string TXT_SEARCH {
            get {
                return ResourceManager.GetString("TXT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder:.
        /// </summary>
        internal static string TXT_SELECT_FOLDER {
            get {
                return ResourceManager.GetString("TXT_SELECT_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for Serial Port: .
        /// </summary>
        internal static string TXT_SERIAL_PORT_NAME {
            get {
                return ResourceManager.GetString("TXT_SERIAL_PORT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Serial Port.
        /// </summary>
        internal static string TXT_SERIALPORTLCFG {
            get {
                return ResourceManager.GetString("TXT_SERIALPORTLCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string TXT_SERVER {
            get {
                return ResourceManager.GetString("TXT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the User Interface Theme (per entire ProTONE Suite):.
        /// </summary>
        internal static string TXT_SETSKIN {
            get {
                return ResourceManager.GetString("TXT_SETSKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Settings.
        /// </summary>
        internal static string TXT_SETTINGS {
            get {
                return ResourceManager.GetString("TXT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the User Interface Language (per entire ProTONE Suite):.
        /// </summary>
        internal static string TXT_SETUILANGUAGE {
            get {
                return ResourceManager.GetString("TXT_SETUILANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show errors.
        /// </summary>
        internal static string TXT_SHOWERROR {
            get {
                return ResourceManager.GetString("TXT_SHOWERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show infos.
        /// </summary>
        internal static string TXT_SHOWINFO {
            get {
                return ResourceManager.GetString("TXT_SHOWINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log file ....
        /// </summary>
        internal static string TXT_SHOWLOG {
            get {
                return ResourceManager.GetString("TXT_SHOWLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show panel splitters in main window.
        /// </summary>
        internal static string TXT_SHOWSPLITTERS {
            get {
                return ResourceManager.GetString("TXT_SHOWSPLITTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show traces.
        /// </summary>
        internal static string TXT_SHOWTRACE {
            get {
                return ResourceManager.GetString("TXT_SHOWTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show warnings.
        /// </summary>
        internal static string TXT_SHOWWARNING {
            get {
                return ResourceManager.GetString("TXT_SHOWWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string TXT_SIZE {
            get {
                return ResourceManager.GetString("TXT_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS4 Proxy.
        /// </summary>
        internal static string TXT_SOCKS4PROXY {
            get {
                return ResourceManager.GetString("TXT_SOCKS4PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5 Proxy.
        /// </summary>
        internal static string TXT_SOCKS5PROXY {
            get {
                return ResourceManager.GetString("TXT_SOCKS5PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify URL:.
        /// </summary>
        internal static string TXT_SPECIFYURL {
            get {
                return ResourceManager.GetString("TXT_SPECIFYURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task succesfull..
        /// </summary>
        internal static string TXT_SUCCESS {
            get {
                return ResourceManager.GetString("TXT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files has completed succesfully..
        /// </summary>
        internal static string TXT_SUCCESS_COPY_TASK {
            get {
                return ResourceManager.GetString("TXT_SUCCESS_COPY_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete files has completed succesfully..
        /// </summary>
        internal static string TXT_SUCCESS_DELETE_TASK {
            get {
                return ResourceManager.GetString("TXT_SUCCESS_DELETE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move files has completed succesfully..
        /// </summary>
        internal static string TXT_SUCCESS_MOVE_TASK {
            get {
                return ResourceManager.GetString("TXT_SUCCESS_MOVE_TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string TXT_SUNDAY {
            get {
                return ResourceManager.GetString("TXT_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string TXT_SYSTEM {
            get {
                return ResourceManager.GetString("TXT_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Tasks ?.
        /// </summary>
        internal static string TXT_TASK_CANCEL {
            get {
                return ResourceManager.GetString("TXT_TASK_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abort the executing tasks ?.
        /// </summary>
        internal static string TXT_TASK_CANCEL_MSG {
            get {
                return ResourceManager.GetString("TXT_TASK_CANCEL_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered string does not represent a valid URL..
        /// </summary>
        internal static string TXT_TCPIPINVALIDFORMAT {
            get {
                return ResourceManager.GetString("TXT_TCPIPINVALIDFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the URL:.
        /// </summary>
        internal static string TXT_TCPIPURI {
            get {
                return ResourceManager.GetString("TXT_TCPIPURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items to show in this panel..
        /// </summary>
        internal static string TXT_THEREARENOITEMS {
            get {
                return ResourceManager.GetString("TXT_THEREARENOITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string TXT_THURSDAY {
            get {
                return ResourceManager.GetString("TXT_THURSDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread ID.
        /// </summary>
        internal static string TXT_TID {
            get {
                return ResourceManager.GetString("TXT_TID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string TXT_TIMESTAMP {
            get {
                return ResourceManager.GetString("TXT_TIMESTAMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show debug traces.
        /// </summary>
        internal static string TXT_TRACE {
            get {
                return ResourceManager.GetString("TXT_TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string TXT_TUESDAY {
            get {
                return ResourceManager.GetString("TXT_TUESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string TXT_UNDO {
            get {
                return ResourceManager.GetString("TXT_UNDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string TXT_UP {
            get {
                return ResourceManager.GetString("TXT_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string TXT_USERNAME {
            get {
                return ResourceManager.GetString("TXT_USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string TXT_VERSION {
            get {
                return ResourceManager.GetString("TXT_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while copying files ....
        /// </summary>
        internal static string TXT_WAIT_COPY {
            get {
                return ResourceManager.GetString("TXT_WAIT_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while deleting files ....
        /// </summary>
        internal static string TXT_WAIT_DELETE {
            get {
                return ResourceManager.GetString("TXT_WAIT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while moving files ....
        /// </summary>
        internal static string TXT_WAIT_MOVE {
            get {
                return ResourceManager.GetString("TXT_WAIT_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while downloading application update files. You can press ESC to abort the download and keep the existing application version..
        /// </summary>
        internal static string TXT_WAITDOWNLOADUPDATE {
            get {
                return ResourceManager.GetString("TXT_WAITDOWNLOADUPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log warning messages.
        /// </summary>
        internal static string TXT_WARNING {
            get {
                return ResourceManager.GetString("TXT_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string TXT_WEDNESDAY {
            get {
                return ResourceManager.GetString("TXT_WEDNESDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        internal static string TXT_WIZARDBACK {
            get {
                return ResourceManager.GetString("TXT_WIZARDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TXT_WIZARDCANCEL {
            get {
                return ResourceManager.GetString("TXT_WIZARDCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string TXT_WIZARDFINISH {
            get {
                return ResourceManager.GetString("TXT_WIZARDFINISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        internal static string TXT_WIZARDNEXT {
            get {
                return ResourceManager.GetString("TXT_WIZARDNEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TXT_WIZARDOK {
            get {
                return ResourceManager.GetString("TXT_WIZARDOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat wizard.
        /// </summary>
        internal static string TXT_WIZARDREPEAT {
            get {
                return ResourceManager.GetString("TXT_WIZARDREPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string TXT_WIZARDSTEPDELIMITER {
            get {
                return ResourceManager.GetString("TXT_WIZARDSTEPDELIMITER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string TXT_WIZARDSTEPTEXT {
            get {
                return ResourceManager.GetString("TXT_WIZARDSTEPTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has finished task execution..
        /// </summary>
        internal static string TXT_WIZFINISHED {
            get {
                return ResourceManager.GetString("TXT_WIZFINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is running, please wait ....
        /// </summary>
        internal static string TXT_WIZFINISHING {
            get {
                return ResourceManager.GetString("TXT_WIZFINISHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string TXT_WIZSTEPRESULTS {
            get {
                return ResourceManager.GetString("TXT_WIZSTEPRESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All wizard tasks have finished succesfully !.
        /// </summary>
        internal static string TXT_WIZTASKSFINISHED {
            get {
                return ResourceManager.GetString("TXT_WIZTASKSFINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All wizard tasks have finished, but some errors were encountered. Details in the list below..
        /// </summary>
        internal static string TXT_WIZTASKSFINISHED_ERRORS {
            get {
                return ResourceManager.GetString("TXT_WIZTASKSFINISHED_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while wizard tasks are running ....
        /// </summary>
        internal static string TXT_WIZTASKSRUNNING {
            get {
                return ResourceManager.GetString("TXT_WIZTASKSRUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program working folder:.
        /// </summary>
        internal static string TXT_WORKDIR {
            get {
                return ResourceManager.GetString("TXT_WORKDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string TXT_YES {
            get {
                return ResourceManager.GetString("TXT_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes for all.
        /// </summary>
        internal static string TXT_YESALL {
            get {
                return ResourceManager.GetString("TXT_YESALL", resourceCulture);
            }
        }
    }
}
